INSERT INTO text (`auteur`, `langue`, `contenu`, `titre`) VALUES
('Agatha Christie', 'anglais', 'IN THE CORNER of a first-class smoking carriage, Mr. Justice Wargrave, lately  retired from the bench, puffed at a cigar and ran an interested eye through the  political news in the Times.   He laid the paper down and glanced out of the window. They were running now   through Somerset. He glanced at his watch-another two hours to go.   He went over in his mind all that had appeared in the papers about Indian Island.   There had been its original purchase by an American millionaire who was crazy   about yachting-and an account of the luxurious modern house he had built on this   little island off the Devon coast. The unfortunate fact that the new third wife   of the American millionaire was a bad sailor had led to the subsequent putting   up of the house and island for sale. Various glowing advertisements of it had   appeared in the papers. Then came the first bald statement that it had been   bought-by a Mr. Owen. After that the rurnours of the gossip writers had started.   Indian Island had really been bought by Miss Gabrielle Turl, the Hollywood film   star! She wanted to spend some months there free from all publicity! Busy Bee had   hinted delicately that it was to be an abode for Royalty??! Mr. Merryweather had   had it whispered to him that it had been bought for a honeymoon-Young Lord L--  had surrendered to Cupid at last! Jonas knew for a fact that it had been   purchased by the Admiralty with a view to carrying out some very hush hush   experiments!   Definitely, Indian Island was news!   From his pocket Mr. Justice Wargrave drew out a letter. The handwriting was   practically illegible but words here and there stood out with unexpected clarity.   Dearest Lawrence . . . such years since I heard anything of you . . . must come   to Indian Island . . . the most enchanting place . . . so much to talk over . .   . old days . . .  communion with Nature . . . bask in sunshine . . . 12.40 from Paddington . . .  meet you at Oakbridge . . . and his correspondent signed herself with a flourish  his ever Constance Culmington.   Mr. Justice Wargrave cast back in his mind to remember when exactly he had last   seen Lady Constance Culmington. It must be seven -no, eight years ago. She had   then been going to Italy to bask in the sun and be at one with Nature and the   contaditd. Later, he had heard, she had proceeded to Syria where she proposed to   bask in yet stronger sun and live at one with Nature and the bedouin.   Constance Culmington, he reflected to himself, was exactly the sort of woman who   would buy an island and surround herself with mystery! Nodding his head in gentle   approval of his logic, Mr. Justice Wargrave allowed his head to nod.  He slept. . . . 
Vera Claythorne, in a third-class carriage with five other travellers in it,   leaned her head back and shut her eyes. How hot it was travelling by train   to-day! It would be nice to get to the sea! Really a great piece of luck getting   this job. When you wanted a holiday post it nearly always meant looking after a   swarm of children-secretarial holiday posts were much more difficult to get. Even   the agency hadn\'t held out much hope.  And then the letter had come. 
"I have received your name from the Skilled Women\'s Agency together with their   recommendation. I understand they know you personally. I shall be glad to pay you   the salary you ask and shall expect you to take up your duties on August 8th. The   train is the 12.40 from Paddington and you will be met at Oakbridge station. I   enclose five pound notes for expenses.
Yours truly,   Una Nancy Owen." 
And at the top was the stamped address Indian Island, Sticklehaven,  Devon. . . .   Indian Island! Why, there had been nothing else in the papers lately! All   sorts of hints and interesting rumours. Though probably', 'andThenThereWereNone'),

('Grimm', 'anglais', 'Near a great forest there lived a poor woodcutter and his wife, and his two children; the boy\'s name was Hansel and the girl\'s Grethel. They had very little to bite or to sup, and once, when there was great dearth in the land, the man could not even gain the daily bread. As he lay in bed one night thinking of this, and turning and tossing, he sighed heavily, and said to his wife, "What will become of us? we cannot even feed our children; there is nothing left for ourselves."
"I will tell you what, husband," answered the wife; "we will take the children early in the morning into the forest, where it is thickest; we will make them a fire, and we will give each of them a piece of bread, then we will go to our work and leave them alone; they will never find the way home again, and we shall be quit of them."
"No, wife," said the man, "I cannot do that; I cannot find in my heart to take my children into the forest and to leave them there alone; the wild animals would soon come and devour them." - "O you fool," said she, "then we will all four starve; you had better get the coffins ready," and she left him no peace until he consented. "But I really pity the poor children," said the man.
The two children had not been able to sleep for hunger, and had heard what their step-mother had said to their father. Grethel wept bitterly, and said to Hansel, "It is all over with us."
"Do be quiet, Grethel," said Hansel, "and do not fret; 1 will manage something." And when the parents had gone to sleep he got up, put on his little coat, opened the back door, and slipped out. The moon was shining brightly, and the white flints that lay in front of the house glistened like pieces of silver. Hansel stooped and filled the little pocket of his coat as full as it would hold. Then he went back again, and said to Grethel, "Be easy, dear little sister, and go to sleep quietly; God will not forsake us," and laid himself down again in his bed. When the day was breaking, and before the sun had risen, the wife came and awakened the two children, saying, "Get up, you lazy bones; we are going into the forest to cut wood." Then she gave each of them a piece of bread, and said, "That is for dinner, and you must not eat it before then, for you will get no more." Grethel carried the bread under her apron, for Hansel had his pockets full of the flints. Then they set off all together on their way to the forest. When they had gone a little way Hansel stood still and looked back towards the house, and this he did again and again, till his father said to him, "Hansel, what are you looking at? take care not to forget your legs."
"O father," said Hansel, "lam looking at my little white kitten, who is sitting up on the roof to bid me good-bye." - "You young fool," said the woman, "that is not your kitten, but the sunshine on the chimney-pot." Of course Hansel had not been looking at his kitten, but had been taking every now and then a flint from his pocket and dropping it on the road. When they reached the middle of the forest the father told the children to collect wood to make a fire to keep them, warm; and Hansel and Grethel gathered brushwood enough for a little mountain j and it was set on fire, and when the flame was burning quite high the wife said, "Now lie down by the fire and rest yourselves, you children, and we will go and cut wood; and when we are ready we will come and fetch you."', 'hansetandgretel'),

('J.K. Rowling', 'anglais', 'The most evil and powerful dark wizard in history, Lord Voldemort, murdered married couple James and Lily Potter but mysteriously disappeared after failing to kill their infant son, Harry. While the wizarding world celebrates Voldemort\'s apparent downfall, Professor Dumbledore, Professor McGonagall and half-giant Rubeus Hagrid place the one-year-old orphan in the care of his surly and cold Muggle uncle and aunt, Vernon and Petunia Dursley and their spoilt and bullying son, Dudley.
For ten years, living at number Four Privet Drive, Harry is treated by the Dursleys more like a servant than a member of the family and is forced to live in a cupboard under the stairs. Shortly before his eleventh birthday, a series of letters addressed to Harry arrive, but Uncle Vernon Dursley destroys them before Harry can read them, leading to an influx of more and more letters. To evade the pursuit of these letters, Vernon first takes the family to a hotel, but when the letters arrive there too, he hires a boat out to a hut on a small island.
It is Harry\'s eleventh birthday and at midnight, Hagrid bursts through the door to deliver the letter and to tell Harry what the Dursleys have kept from him: Harry is a wizard and has been accepted into Hogwarts School of Witchcraft and Wizardry. Hagrid takes Harry to a hidden London street called Diagon Alley, where he is surprised to discover how famous he is among the witches and wizards, who refer to him as "the boy who lived." He also finds that his parents\' inheritance is waiting for him at Gringotts Wizarding Bank. Guided by Hagrid, he buys the equipment he will need for his first year at Hogwarts and as a birthday gift Harry receives a pet owl from Hagrid (which he names "Hedwig").
A month later, Harry leaves the Dursleys\' home to catch the Hogwarts Express from King\'s Cross railway station. There he meets the Weasley family, who show him how to pass through the magic wall to Platform 9æ, where the train that will take them to Hogwarts is waiting. While on the train, Harry meets two fellow first years, Ron Weasley, who immediately becomes his friend, and Hermione Granger, with whom the ice is a bit slower to break. Harry also makes an enemy of yet another first-year, Draco Malfoy. Draco offers to advise Harry, but Harry dislikes Draco for his arrogance and prejudice and rejects his offer of "friendship".
At Hogwarts, the first-years are assigned by the magical Sorting Hat to houses that best suit their personalities. While Harry is being sorted, the Hat suggests that he be placed into Slytherin which is known to house potential dark witches and wizards, but when Harry objects, the Hat sends him to Gryffindor. Ron and Hermione are also sorted into Gryffindor. Draco is sorted into Slytherin, like his whole family before him.
Harry starts classes at Hogwarts School, with lessons including Transfiguration with Head of Gryffindor, Minerva McGonagall, Herbology with Head of Hufflepuff, Pomona Sprout, Charms with Head of Ravenclaw Filius Flitwick, and Defence Against the Dark Arts with Quirinus Quirrell. Harry\'s least favourite class is Potions, taught by Severus Snape, the vindictive Head of Slytherin who seems to loathe Harry. Harry, Ron, and Hermione become far more interested by extracurricular matters within and outside of the school, particularly after they discover that a huge three-headed dog is standing guard over a trap door in a forbidden corridor. They also become suspicious of Snape\'s behaviour and become convinced that he is looking for ways to get past the trapdoor.
Harry discovers an innate talent for flying on broomsticks and is appointed as Seeker on his Houseís Quidditch team, a wizards\'s sport played in the air. His first game goes well until his broomstick wobbles in mid-air and almost throws him off. Ron and Hermione suspect foul play from Snape, whom they saw behaving oddly. For Christmas, Harry receives an invisibility cloak from an anonymous source and begins exploring the school at night and investigating the hidden object further. He discovers the Mirror of Erised, in which the viewer sees his deepest desires becoming true.
Thanks to an indiscretion from Hagrid, Harry and his friends work out that the object kept at the school is a Philosopher\'s Stone, made by an old friend of Dumbledore named Nicolas Flamel. Harry is also informed by a centaur he meets in the forest that a plot to steal the Philosopherís Stone is being orchestrated by none other than Voldemort himself, who would use it to be restored to his body and come back to power. When Dumbledore is lured from Hogwarts under false pretences, Harry and his friends fear that the theft is imminent and descend through the trapdoor themselves.
They encounter a series of obstacles, each of which requires unique skills possessed by one of the three, and one of which requires Ron to sacrifice himself in a life-sized game of wizard\'s chess. In the final room, Harry, now alone, finds Quirrell, who admits that he had tried to kill Harry at his Quidditch match against Slytherin. He also admits that he let a troll into Hogwarts. Snape had been trying to protect Harry all along rather than to kill him, and his suspicious behaviour came from his own suspicions about Quirrell.
Quirrell is one of Voldemort\'s followers, and is now partly possessed by him: Voldemort\'s face has sprouted on the back of his own head, hidden by his turban. Voldemort needs Harry\'s help to get past the final obstacle: the Mirror of Erised, but when Quirrell tries to grab the Stone from Harry his contact proves lethal for Quirrell. Harry passes out and awakes in the school hospital, where Dumbledore explains to him that he survived because his mother sacrificed her life to protect him, and this left a powerful protective charm on him. Voldemort left Quirrell to die and is likely to return by some other means. The Stone has now been destroyed. The school year ends at the final feast, during which Gryffindor wins the House Cup. Harry returns to the Dursleys\' for the summer holiday but does not tell them that under-age wizards are forbidden to use magic outside of Hogwarts.', 'harryPotter'),

('Henry Esmond', 'anglais', 'Using sporadically the first and third persons, Henry Esmond relates his own history in memoir fashion. The novel opens on Henry as a boy ñ the supposedly illegitimate (and eventually orphaned) son of Thomas, the third Viscount Castlewood, and cousin of the Jacobite fourth viscount, Francis, and his wife, the Lady Castlewood. These successors to the Castlewood estate and peerage, following the death of Henry\'s father, foster the boy, and he remains with them throughout his youth and early adulthood.
A quiet, sober, hard-working youth, Henry is devoted to his foster family. Gentle, sensitive Lady Castlewood is his adored mother figure. Her husband is also kind to Esmond, but the hard-drinking viscount is clearly a man of limited intellect whose crude manners and thoughtless ways cause his wife a great deal of embarrassment and pain.
Henry Esmond knows that his cousinsódull, good-natured Frank and sly, seductive Beatrixówill eventually inherit Castlewood. After the heartless Beatrix rejects his offer of marriage, he journeys to London to make his fortune. Esmond meets many of the celebrated English writers of the day, such as Joseph Addison and Richard Steele. Addison and Steele are both represented as model English gentlemen, who gladly mentor Esmond in his literary career, while the equally noted Jonathan Swift is depicted in most unflattering terms as a hateful misanthrope and bully. Particular venom is directed at Swift for the abundant leisure he had at the vicarage in Trim, County Meath for cultivating his garden, making a canal (after the Dutch fashion of Moor Park), and planting willows.
When his writing career stalls, Esmond joins the British army. Here he is reunited with his cousin Frank, who is now a dashing but foolhardy young officer. The two cousins later join the unsuccessful campaign to restore James Francis Edward Stuart to the English throne. After much intrigue, Esmond grows disillusioned with Jacobitism and eventually comes to accept the Protestant future of England. He falls in love with his cousin (daughter of his patron, Castlewood), Beatrix, but eventually marries his foster-mother (also his cousin, and Beatrix\'s mother), Rachel, Lady Castlewood. The novel closes on the couple\'s emigration to Virginia in 1718.', 'henryEsmond'),

('Grid Bluton', 'anglais', 'Big-Ears the brownie was hurrying through the woods on his little red bicycle, when he suddenly bumped into somebody. Down they went, and the bicycle fell on top of Big-Ears with a crash.
You\'re a rather peculiar-looking person, said Big-Ears, rubbing his head. What are you? You\'re not a pixie or a brownie or a goblin, are you? No, said the person, nodding his head.
Are you a toy? asked Big-Ears. 
No, I don\'t think so, said the stranger, nodding his head. 
Why do you nod your head when you say no ? asked Big-Ears, still staring. 
Because I\'m a little nodding man,I said the small fellow. My head\'s balanced on my neck in such a way that I have to nod when I speak. Oooh  what\'s that? Is it somebody after me?
No. It\'s only a field-mouse scurrying by, said Big-Ears, getting up.  Why are you so afraid?
Because I\'ve run away! said the nodding man. I belonged to Old Man Carver, who lives in the woods. He made me. 
Did he really? said Big-Ears. How did he make you? 
He made wooden feet, and then wooden legs, and then a round wooden body, and then wooden arms and hands, and then a wooden neck, and then a round wooden head, said the little man.
And did he stick them all together and make you? asked Big-Ears. You\'ve got funny eyes  and funny hair, too. What are they made of?
The old man made holes in my wooden head and then pushed blue beads into the holes, said the nodding man. That\'s why I\'ve got such bright blue eyes. He made my hair out of bits of fur from his cat\'s back. The cat said he could.
Well, why are you running away? asked Big-Ears.
I was lonely, said the little man. I want to go and live somewhere where there are lots and lots of people.
Then I really think you ought to live in Toyland, said  Big-Ears. You\'re not a brownie, so you can\'t live in my town.  You\'re not exactly a toy either, but you\'re very much like one. You\'d better go to Toyland.
I don\'t know the way, said the little nodding man sadly.
Well, I do,í said Big-Ears. ëStand on the step of my bicycle and I\'ll take you to catch the Toyland train.
The nodding man did as he was told, clutching at the brownie\'s pointed ears in fright.
What\'s your name? shouted Big-Ears, as they went along. Hey! Let go of my ears! Tell me your name!
I haven\'t got one,í said the nodding man. What do you suppose my name ought to be, brownie?
Noddy, I should think! said Big-Ears. Yes ! I think your name is Noddy, little nodding man.', 'noddy');