INSERT INTO mot_dico (`valeur`, `langue`) VALUES
('a', 'Anglais'),
('abandon', 'Anglais'),
('abandoned', 'Anglais'),
('ability', 'Anglais'),
('able', 'Anglais'),
('about', 'Anglais'),
('above', 'Anglais'),
('abroad', 'Anglais'),
('absence', 'Anglais'),
('absent', 'Anglais'),
('absolute', 'Anglais'),
('absolutely', 'Anglais'),
('absorb', 'Anglais'),
('abuse', 'Anglais'),
('abuse', 'Anglais'),
('academic', 'Anglais'),
('accent', 'Anglais'),
('accept', 'Anglais'),
('acceptable', 'Anglais'),
('access', 'Anglais'),
('accident', 'Anglais'),
('accidental', 'Anglais'),
('accidentally', 'Anglais'),
('accommodation', 'Anglais'),
('accompany', 'Anglais'),
('according to', 'Anglais'),
('account', 'Anglais'),
('account for', 'Anglais'),
('accurate', 'Anglais'),
('accurately', 'Anglais'),
('accuse', 'Anglais'),
('achieve', 'Anglais'),
('achievement', 'Anglais'),
('acid', 'Anglais'),
('acknowledge', 'Anglais'),
('a couple', 'Anglais'),
('acquire', 'Anglais'),
('across', 'Anglais'),
('act', 'Anglais'),
('action', 'Anglais'),
('active', 'Anglais'),
('actively', 'Anglais'),
('activity', 'Anglais'),
('actor', 'Anglais'),
('actress', 'Anglais'),
('actual', 'Anglais'),
('actually', 'Anglais'),
('ad', 'Anglais'),
('adapt', 'Anglais'),
('add', 'Anglais'),
('addition', 'Anglais'),
('additional', 'Anglais'),
('add on', 'Anglais'),
('address', 'Anglais'),
('add up', 'Anglais'),
('add up to', 'Anglais'),
('adequate', 'Anglais'),
('adequately', 'Anglais'),
('adjust', 'Anglais'),
('admiration', 'Anglais'),
('admire', 'Anglais'),
('admit', 'Anglais'),
('adopt', 'Anglais'),
('adult', 'Anglais'),
('advance', 'Anglais'),
('advanced', 'Anglais'),
('advantage', 'Anglais'),
('adventure', 'Anglais'),
('advert', 'Anglais'),
('advertise', 'Anglais'),
('advertisement', 'Anglais'),
('advertising', 'Anglais'),
('advice', 'Anglais'),
('advise', 'Anglais'),
('affair', 'Anglais'),
('affect', 'Anglais'),
('affection', 'Anglais'),
('afford', 'Anglais'),
('afraid', 'Anglais'),
('after', 'Anglais'),
('afternoon', 'Anglais'),
('afterwards', 'Anglais'),
('again', 'Anglais'),
('against', 'Anglais'),
('age', 'Anglais'),
('aged', 'Anglais'),
('agency', 'Anglais'),
('agent', 'Anglais'),
('aggressive', 'Anglais'),
('ago', 'Anglais'),
('agree', 'Anglais'),
('agreement', 'Anglais'),
('ahead', 'Anglais'),
('aid', 'Anglais'),
('aim', 'Anglais'),
('air', 'Anglais'),
('aircraft', 'Anglais'),
('airport', 'Anglais'),
('alarm', 'Anglais'),
('alarmed', 'Anglais'),
('alarming', 'Anglais'),
('alcohol', 'Anglais'),
('alcoholic', 'Anglais'),
('alive', 'Anglais'),
('all', 'Anglais'),
('allied', 'Anglais'),
('allow', 'Anglais'),
('allow for', 'Anglais'),
('all right', 'Anglais'),
('ally', 'Anglais'),
('almost', 'Anglais'),
('alone', 'Anglais'),
('along', 'Anglais'),
('alongside', 'Anglais'),
('aloud', 'Anglais'),
('alphabet', 'Anglais'),
('alphabetical', 'Anglais'),
('alphabetically', 'Anglais'),
('already', 'Anglais'),
('also', 'Anglais'),
('alter', 'Anglais'),
('alternative', 'Anglais'),
('alternatively', 'Anglais'),
('although', 'Anglais'),
('altogether', 'Anglais'),
('always', 'Anglais'),
('a.m.', 'Anglais'),
('amaze', 'Anglais'),
('amazed', 'Anglais'),
('amazing', 'Anglais'),
('ambition', 'Anglais'),
('ambulance', 'Anglais'),
('among', 'Anglais'),
('amount', 'Anglais'),
('amount to', 'Anglais'),
('amuse', 'Anglais'),
('amused', 'Anglais'),
('amusing', 'Anglais'),
('analyse', 'Anglais'),
('analysis', 'Anglais'),
('ancient', 'Anglais'),
('and', 'Anglais'),
('anger', 'Anglais'),
('angle', 'Anglais'),
('angrily', 'Anglais'),
('angry', 'Anglais'),
('animal', 'Anglais'),
('ankle', 'Anglais'),
('anniversary', 'Anglais'),
('announce', 'Anglais'),
('annoy', 'Anglais'),
('annoyed', 'Anglais'),
('annoying', 'Anglais'),
('annual', 'Anglais'),
('annually', 'Anglais'),
('another', 'Anglais'),
('answer', 'Anglais'),
('anti-', 'Anglais'),
('anticipate', 'Anglais'),
('anxiety', 'Anglais'),
('anxious', 'Anglais'),
('anxiously', 'Anglais'),
('any', 'Anglais'),
('anybody', 'Anglais'),
('anyone', 'Anglais'),
('anything', 'Anglais'),
('anyway', 'Anglais'),
('anywhere', 'Anglais'),
('apart', 'Anglais'),
('apart from', 'Anglais'),
('apartment', 'Anglais'),
('apologize', 'Anglais'),
('apparent', 'Anglais'),
('apparently', 'Anglais'),
('appeal', 'Anglais'),
('appear', 'Anglais'),
('appearance', 'Anglais'),
('apple', 'Anglais'),
('application', 'Anglais'),
('apply', 'Anglais'),
('appoint', 'Anglais'),
('appointment', 'Anglais'),
('appreciate', 'Anglais'),
('approach', 'Anglais'),
('appropriate', 'Anglais'),
('approval', 'Anglais'),
('approve', 'Anglais'),
('approving', 'Anglais'),
('approximate', 'Anglais'),
('approximately', 'Anglais'),
('April', 'Anglais'),
('area', 'Anglais'),
('argue', 'Anglais'),
('argument', 'Anglais'),
('arise', 'Anglais'),
('arm', 'Anglais'),
('armed', 'Anglais'),
('arms', 'Anglais'),
('army', 'Anglais'),
('around', 'Anglais'),
('arrange', 'Anglais'),
('arrangement', 'Anglais'),
('arrest', 'Anglais'),
('arrival', 'Anglais'),
('arrive', 'Anglais'),
('arrive at', 'Anglais'),
('arrow', 'Anglais'),
('art', 'Anglais'),
('article', 'Anglais'),
('artificial', 'Anglais'),
('artificially', 'Anglais'),
('artist', 'Anglais'),
('artistic', 'Anglais'),
('artistically', 'Anglais'),
('as', 'Anglais'),
('ashamed', 'Anglais'),
('aside', 'Anglais'),
('aside from', 'Anglais'),
('ask', 'Anglais'),
('asleep', 'Anglais'),
('aspect', 'Anglais'),
('assist', 'Anglais'),
('assistance', 'Anglais'),
('assistant', 'Anglais'),
('associate', 'Anglais'),
('associated', 'Anglais'),
('association', 'Anglais'),
('assume', 'Anglais'),
('assure', 'Anglais'),
('at', 'Anglais'),
('atmosphere', 'Anglais'),
('atom', 'Anglais'),
('attach', 'Anglais'),
('attached', 'Anglais'),
('attack', 'Anglais'),
('attempt', 'Anglais'),
('attempted', 'Anglais'),
('attend', 'Anglais'),
('attend to', 'Anglais'),
('attention', 'Anglais'),
('attitude', 'Anglais'),
('attorney', 'Anglais'),
('attract', 'Anglais'),
('attraction', 'Anglais'),
('attractive', 'Anglais'),
('audience', 'Anglais'),
('August', 'Anglais'),
('aunt', 'Anglais'),
('author', 'Anglais'),
('authority', 'Anglais'),
('automatic', 'Anglais'),
('automatically', 'Anglais'),
('autumn', 'Anglais'),
('available', 'Anglais'),
('average', 'Anglais'),
('avoid', 'Anglais'),
('awake', 'Anglais'),
('award', 'Anglais'),
('aware', 'Anglais'),
('away', 'Anglais'),
('awful', 'Anglais'),
('awfully', 'Anglais'),
('awkward', 'Anglais'),
('awkwardly', 'Anglais'),
('baby', 'Anglais'),
('back', 'Anglais'),
('background', 'Anglais'),
('back up', 'Anglais'),
('backward', 'Anglais'),
('backwards', 'Anglais'),
('bacteria', 'Anglais'),
('bad', 'Anglais'),
('badly', 'Anglais'),
('bad-tempered', 'Anglais'),
('bag', 'Anglais'),
('baggage', 'Anglais'),
('bake', 'Anglais'),
('balance', 'Anglais'),
('ball', 'Anglais'),
('ban', 'Anglais'),
('band', 'Anglais'),
('bandage', 'Anglais'),
('bank', 'Anglais'),
('bar', 'Anglais'),
('bargain', 'Anglais'),
('barrier', 'Anglais'),
('base', 'Anglais'),
('based', 'Anglais'),
('base on', 'Anglais'),
('basic', 'Anglais'),
('basically', 'Anglais'),
('basis', 'Anglais'),
('bath', 'Anglais'),
('bathroom', 'Anglais'),
('battery', 'Anglais'),
('battle', 'Anglais'),
('bay', 'Anglais'),
('be', 'Anglais'),
('beach', 'Anglais'),
('beak', 'Anglais'),
('bear', 'Anglais'),
('beard', 'Anglais'),
('beat', 'Anglais'),
('beat up', 'Anglais'),
('beautiful', 'Anglais'),
('beautifully', 'Anglais'),
('beauty', 'Anglais'),
('because', 'Anglais'),
('because of', 'Anglais'),
('become', 'Anglais'),
('bed', 'Anglais'),
('bedroom', 'Anglais'),
('beef', 'Anglais'),
('beer', 'Anglais'),
('before', 'Anglais'),
('begin', 'Anglais'),
('beginning', 'Anglais'),
('behalf', 'Anglais'),
('behave', 'Anglais'),
('behaviour', 'Anglais'),
('behind', 'Anglais'),
('be left over', 'Anglais'),
('belief', 'Anglais'),
('believe', 'Anglais'),
('believe in', 'Anglais'),
('bell', 'Anglais'),
('belong', 'Anglais'),
('belong to', 'Anglais'),
('below', 'Anglais'),
('belt', 'Anglais'),
('bend', 'Anglais'),
('beneath', 'Anglais'),
('benefit', 'Anglais'),
('bent', 'Anglais'),
('beside', 'Anglais'),
('best', 'Anglais'),
('bet', 'Anglais'),
('better', 'Anglais'),
('betting', 'Anglais'),
('between', 'Anglais'),
('beyond', 'Anglais'),
('bicycle', 'Anglais'),
('bid 1', 'Anglais'),
('big', 'Anglais'),
('bike', 'Anglais'),
('bill', 'Anglais'),
('billion', 'Anglais'),
('bin', 'Anglais'),
('biology', 'Anglais'),
('bird', 'Anglais'),
('birth', 'Anglais'),
('birthday', 'Anglais'),
('biscuit', 'Anglais'),
('bit', 'Anglais'),
('bite', 'Anglais'),
('bitter', 'Anglais'),
('bitterly', 'Anglais'),
('black', 'Anglais'),
('blade', 'Anglais'),
('blame', 'Anglais'),
('blank', 'Anglais'),
('blind', 'Anglais'),
('block', 'Anglais'),
('blonde', 'Anglais'),
('blood', 'Anglais'),
('blow', 'Anglais'),
('blow out', 'Anglais'),
('blow up', 'Anglais'),
('blue', 'Anglais'),
('board', 'Anglais'),
('boat', 'Anglais'),
('body', 'Anglais'),
('boil', 'Anglais'),
('bomb', 'Anglais'),
('bone', 'Anglais'),
('book', 'Anglais'),
('boot', 'Anglais'),
('border', 'Anglais'),
('bore', 'Anglais'),
('bored', 'Anglais'),
('boring', 'Anglais'),
('born', 'Anglais'),
('borrow', 'Anglais'),
('boss', 'Anglais'),
('both', 'Anglais'),
('bother', 'Anglais'),
('bottle', 'Anglais'),
('bottom', 'Anglais'),
('bound', 'Anglais'),
('bowl', 'Anglais'),
('box', 'Anglais'),
('boy', 'Anglais'),
('boyfriend', 'Anglais'),
('brain', 'Anglais'),
('branch', 'Anglais'),
('brand', 'Anglais'),
('brave', 'Anglais'),
('bread', 'Anglais'),
('break', 'Anglais'),
('break down', 'Anglais'),
('breakfast', 'Anglais'),
('break in', 'Anglais'),
('break into', 'Anglais'),
('break off', 'Anglais'),
('break out', 'Anglais'),
('break up', 'Anglais'),
('breast', 'Anglais'),
('breath', 'Anglais'),
('breathe', 'Anglais'),
('breathe in', 'Anglais'),
('breathe out', 'Anglais'),
('breathing', 'Anglais'),
('breed', 'Anglais'),
('brick', 'Anglais'),
('bridge', 'Anglais'),
('brief', 'Anglais'),
('briefly', 'Anglais'),
('bright', 'Anglais'),
('brightly', 'Anglais'),
('brilliant', 'Anglais'),
('bring', 'Anglais'),
('bring back', 'Anglais'),
('bring down', 'Anglais'),
('bring forward', 'Anglais'),
('bring out', 'Anglais'),
('bring up', 'Anglais'),
('broad', 'Anglais'),
('broadcast', 'Anglais'),
('broadly', 'Anglais'),
('broken', 'Anglais'),
('brother', 'Anglais'),
('brown', 'Anglais'),
('brush', 'Anglais'),
('bubble', 'Anglais'),
('budget', 'Anglais'),
('build', 'Anglais'),
('building', 'Anglais'),
('build up', 'Anglais'),
('bullet', 'Anglais'),
('bunch', 'Anglais'),
('burn', 'Anglais'),
('burn down', 'Anglais'),
('burnt', 'Anglais'),
('burst', 'Anglais'),
('burst into', 'Anglais'),
('burst out', 'Anglais'),
('bury', 'Anglais'),
('bus', 'Anglais'),
('bush', 'Anglais'),
('business', 'Anglais'),
('businessman', 'Anglais'),
('busy', 'Anglais'),
('but', 'Anglais'),
('butter', 'Anglais'),
('button', 'Anglais'),
('buy', 'Anglais'),
('buyer', 'Anglais'),
('by', 'Anglais'),
('bye', 'Anglais'),
('cabinet', 'Anglais'),
('cable', 'Anglais'),
('cake', 'Anglais'),
('calculate', 'Anglais'),
('calculation', 'Anglais'),
('call', 'Anglais'),
('call back', 'Anglais'),
('called', 'Anglais'),
('call for', 'Anglais'),
('call off', 'Anglais'),
('call up', 'Anglais'),
('calm', 'Anglais'),
('calm down', 'Anglais'),
('calmly', 'Anglais'),
('camera', 'Anglais'),
('camp', 'Anglais'),
('campaign', 'Anglais'),
('camping', 'Anglais'),
('can 1', 'Anglais'),
('can 2', 'Anglais'),
('cancel', 'Anglais'),
('cancer', 'Anglais'),
('candidate', 'Anglais'),
('candy', 'Anglais'),
('cannot', 'Anglais'),
('cap', 'Anglais'),
('capable', 'Anglais'),
('capacity', 'Anglais'),
('capital', 'Anglais'),
('captain', 'Anglais'),
('capture', 'Anglais'),
('car', 'Anglais'),
('card', 'Anglais'),
('cardboard', 'Anglais'),
('care', 'Anglais'),
('career', 'Anglais'),
('care for', 'Anglais'),
('careful', 'Anglais'),
('carefully', 'Anglais'),
('careless', 'Anglais'),
('carelessly', 'Anglais'),
('carpet', 'Anglais'),
('carrot', 'Anglais'),
('carry', 'Anglais'),
('carry on', 'Anglais'),
('carry out', 'Anglais'),
('case', 'Anglais'),
('cash', 'Anglais'),
('cast', 'Anglais'),
('castle', 'Anglais'),
('cat', 'Anglais'),
('catch', 'Anglais'),
('catch up', 'Anglais'),
('category', 'Anglais'),
('cause', 'Anglais'),
('CD', 'Anglais'),
('cease', 'Anglais'),
('ceiling', 'Anglais'),
('celebrate', 'Anglais'),
('celebration', 'Anglais'),
('cell', 'Anglais'),
('cell phone', 'Anglais'),
('cent', 'Anglais'),
('centimetre', 'Anglais'),
('central', 'Anglais'),
('centre', 'Anglais'),
('century', 'Anglais'),
('ceremony', 'Anglais'),
('certain', 'Anglais'),
('certainly', 'Anglais'),
('certificate', 'Anglais'),
('chain', 'Anglais'),
('chair', 'Anglais'),
('chairman', 'Anglais'),
('chairwoman', 'Anglais'),
('challenge', 'Anglais'),
('chamber', 'Anglais'),
('chance', 'Anglais'),
('change', 'Anglais'),
('change round', 'Anglais'),
('channel', 'Anglais'),
('chapter', 'Anglais'),
('character', 'Anglais'),
('characteristic', 'Anglais'),
('charge', 'Anglais'),
('charity', 'Anglais'),
('chart', 'Anglais'),
('chase', 'Anglais'),
('chase away', 'Anglais'),
('chat', 'Anglais'),
('cheap', 'Anglais'),
('cheaply', 'Anglais'),
('cheat', 'Anglais'),
('cheat of', 'Anglais'),
('check', 'Anglais'),
('check in', 'Anglais'),
('check into', 'Anglais'),
('check on', 'Anglais'),
('check out', 'Anglais'),
('check over', 'Anglais'),
('check up on', 'Anglais'),
('cheek', 'Anglais'),
('cheerful', 'Anglais'),
('cheerfully', 'Anglais'),
('cheese', 'Anglais'),
('chemical', 'Anglais'),
('chemist', 'Anglais'),
('chemistry', 'Anglais'),
('cheque', 'Anglais'),
('chest', 'Anglais'),
('chew', 'Anglais'),
('chicken', 'Anglais'),
('chief', 'Anglais'),
('child', 'Anglais'),
('chin', 'Anglais'),
('chip', 'Anglais'),
('chocolate', 'Anglais'),
('choice', 'Anglais'),
('choose', 'Anglais'),
('chop', 'Anglais'),
('chop down', 'Anglais'),
('chop off', 'Anglais'),
('church', 'Anglais'),
('cigarette', 'Anglais'),
('cinema', 'Anglais'),
('circle', 'Anglais'),
('circumstance', 'Anglais'),
('citizen', 'Anglais'),
('city', 'Anglais'),
('civil', 'Anglais'),
('claim', 'Anglais'),
('clap', 'Anglais'),
('class', 'Anglais'),
('classic', 'Anglais'),
('classroom', 'Anglais'),
('clean', 'Anglais'),
('clean up', 'Anglais'),
('clear', 'Anglais'),
('clearly', 'Anglais'),
('clear out', 'Anglais'),
('clear up', 'Anglais'),
('clerk', 'Anglais'),
('clever', 'Anglais'),
('click', 'Anglais'),
('client', 'Anglais'),
('climate', 'Anglais'),
('climb', 'Anglais'),
('climbing', 'Anglais'),
('clock', 'Anglais'),
('close 1', 'Anglais'),
('close 2', 'Anglais'),
('closed', 'Anglais'),
('closely', 'Anglais'),
('closet', 'Anglais'),
('cloth', 'Anglais'),
('clothes', 'Anglais'),
('clothing', 'Anglais'),
('cloud', 'Anglais'),
('club', 'Anglais'),
('coach', 'Anglais'),
('coal', 'Anglais'),
('coast', 'Anglais'),
('coat', 'Anglais'),
('code', 'Anglais'),
('coffee', 'Anglais'),
('coin', 'Anglais'),
('cold', 'Anglais'),
('coldly', 'Anglais'),
('collapse', 'Anglais'),
('colleague', 'Anglais'),
('collect', 'Anglais'),
('collection', 'Anglais'),
('college', 'Anglais'),
('colour', 'Anglais'),
('coloured', 'Anglais'),
('column', 'Anglais'),
('combination', 'Anglais'),
('combine', 'Anglais'),
('come', 'Anglais'),
('come across', 'Anglais'),
('come down', 'Anglais'),
('comedy', 'Anglais'),
('come from', 'Anglais'),
('come in', 'Anglais'),
('come off', 'Anglais'),
('come on', 'Anglais'),
('come out', 'Anglais'),
('come round', 'Anglais'),
('come to', 'Anglais'),
('come up', 'Anglais'),
('come up to', 'Anglais'),
('comfort', 'Anglais'),
('comfortable', 'Anglais'),
('comfortably', 'Anglais'),
('command', 'Anglais'),
('comment', 'Anglais'),
('commercial', 'Anglais'),
('commission', 'Anglais'),
('commit', 'Anglais'),
('commitment', 'Anglais'),
('committee', 'Anglais'),
('common', 'Anglais'),
('commonly', 'Anglais'),
('communicate', 'Anglais'),
('communication', 'Anglais'),
('community', 'Anglais'),
('company', 'Anglais'),
('compare', 'Anglais'),
('comparison', 'Anglais'),
('compete', 'Anglais'),
('competition', 'Anglais'),
('competitive', 'Anglais'),
('complain', 'Anglais'),
('complaint', 'Anglais'),
('complete', 'Anglais'),
('completely', 'Anglais'),
('complex', 'Anglais'),
('complicate', 'Anglais'),
('complicated', 'Anglais'),
('computer', 'Anglais'),
('concentrate', 'Anglais'),
('concentrate on', 'Anglais'),
('concentration', 'Anglais'),
('concept', 'Anglais'),
('concern', 'Anglais'),
('concerned', 'Anglais'),
('concerning', 'Anglais'),
('concert', 'Anglais'),
('conclude', 'Anglais'),
('conclusion', 'Anglais'),
('concrete', 'Anglais'),
('condition', 'Anglais'),
('conduct', 'Anglais'),
('conduct', 'Anglais'),
('conference', 'Anglais'),
('confidence', 'Anglais'),
('confident', 'Anglais'),
('confidently', 'Anglais'),
('confine', 'Anglais'),
('confined', 'Anglais'),
('confirm', 'Anglais'),
('conflict', 'Anglais'),
('confront', 'Anglais'),
('confuse', 'Anglais'),
('confused', 'Anglais'),
('confusing', 'Anglais'),
('confusion', 'Anglais'),
('congratulate', 'Anglais'),
('congratulation', 'Anglais'),
('congress', 'Anglais'),
('connect', 'Anglais'),
('connected', 'Anglais'),
('connection', 'Anglais'),
('conscious', 'Anglais'),
('consequence', 'Anglais'),
('conservative', 'Anglais'),
('consider', 'Anglais'),
('considerable', 'Anglais'),
('considerably', 'Anglais'),
('consideration', 'Anglais'),
('consist', 'Anglais'),
('consist of', 'Anglais'),
('constant', 'Anglais'),
('constantly', 'Anglais'),
('construct', 'Anglais'),
('construction', 'Anglais'),
('consult', 'Anglais'),
('consumer', 'Anglais'),
('contact', 'Anglais'),
('contain', 'Anglais'),
('container', 'Anglais'),
('contemporary', 'Anglais'),
('content 1', 'Anglais'),
('contest', 'Anglais'),
('context', 'Anglais'),
('continent', 'Anglais'),
('continue', 'Anglais'),
('continuous', 'Anglais'),
('continuously', 'Anglais'),
('contract', 'Anglais'),
('contract', 'Anglais'),
('contrast', 'Anglais'),
('contrast', 'Anglais'),
('contrasting', 'Anglais'),
('contribute', 'Anglais'),
('contribution', 'Anglais'),
('control', 'Anglais'),
('controlled', 'Anglais'),
('convenient', 'Anglais'),
('convention', 'Anglais'),
('conventional', 'Anglais'),
('conversation', 'Anglais'),
('convert', 'Anglais'),
('convince', 'Anglais'),
('cook', 'Anglais'),
('cooker', 'Anglais'),
('cookie', 'Anglais'),
('cooking', 'Anglais'),
('cool', 'Anglais'),
('cool down', 'Anglais'),
('cope', 'Anglais'),
('copy', 'Anglais'),
('core', 'Anglais'),
('corner', 'Anglais'),
('correct', 'Anglais'),
('correctly', 'Anglais'),
('cost', 'Anglais'),
('cottage', 'Anglais'),
('cotton', 'Anglais'),
('cough', 'Anglais'),
('coughing', 'Anglais'),
('could', 'Anglais'),
('council', 'Anglais'),
('count', 'Anglais'),
('counter', 'Anglais'),
('count on', 'Anglais'),
('country', 'Anglais'),
('countryside', 'Anglais'),
('county', 'Anglais'),
('couple', 'Anglais'),
('courage', 'Anglais'),
('course', 'Anglais'),
('court', 'Anglais'),
('cousin', 'Anglais'),
('cover', 'Anglais'),
('covered', 'Anglais'),
('covering', 'Anglais'),
('cover up', 'Anglais'),
('cow', 'Anglais'),
('crack', 'Anglais'),
('cracked', 'Anglais'),
('craft', 'Anglais'),
('crash', 'Anglais'),
('crazy', 'Anglais'),
('cream', 'Anglais'),
('create', 'Anglais'),
('creature', 'Anglais'),
('credit', 'Anglais'),
('credit card', 'Anglais'),
('crime', 'Anglais'),
('criminal', 'Anglais'),
('crisis', 'Anglais'),
('crisp', 'Anglais'),
('criterion', 'Anglais'),
('critical', 'Anglais'),
('criticism', 'Anglais'),
('criticize', 'Anglais'),
('crop', 'Anglais'),
('cross', 'Anglais'),
('cross out', 'Anglais'),
('crowd', 'Anglais'),
('crowded', 'Anglais'),
('crown', 'Anglais'),
('crucial', 'Anglais'),
('cruel', 'Anglais'),
('crush', 'Anglais'),
('cry', 'Anglais'),
('cry out', 'Anglais'),
('cultural', 'Anglais'),
('culture', 'Anglais'),
('cup', 'Anglais'),
('cupboard', 'Anglais'),
('curb', 'Anglais'),
('cure', 'Anglais'),
('curious', 'Anglais'),
('curiously', 'Anglais'),
('curl', 'Anglais'),
('curl up', 'Anglais'),
('curly', 'Anglais'),
('current', 'Anglais'),
('currently', 'Anglais'),
('curtain', 'Anglais'),
('curve', 'Anglais'),
('curved', 'Anglais'),
('custom', 'Anglais'),
('customer', 'Anglais'),
('customs', 'Anglais'),
('cut', 'Anglais'),
('cut back', 'Anglais'),
('cut down', 'Anglais'),
('cut off', 'Anglais'),
('cut out', 'Anglais'),
('cut up', 'Anglais'),
('cycle', 'Anglais'),
('cycling', 'Anglais'),
('dad', 'Anglais'),
('daily', 'Anglais'),
('damage', 'Anglais'),
('damp', 'Anglais'),
('dance', 'Anglais'),
('dancer', 'Anglais'),
('dancing', 'Anglais'),
('danger', 'Anglais'),
('dangerous', 'Anglais'),
('dare', 'Anglais'),
('dark', 'Anglais'),
('data', 'Anglais'),
('date', 'Anglais'),
('date back', 'Anglais'),
('daughter', 'Anglais'),
('day', 'Anglais'),
('dead', 'Anglais'),
('deaf', 'Anglais'),
('deal', 'Anglais'),
('deal in', 'Anglais'),
('deal with', 'Anglais'),
('dear', 'Anglais'),
('death', 'Anglais'),
('debate', 'Anglais'),
('debt', 'Anglais'),
('decade', 'Anglais'),
('decay', 'Anglais'),
('December', 'Anglais'),
('decide', 'Anglais'),
('decide on', 'Anglais'),
('decision', 'Anglais'),
('declare', 'Anglais'),
('decline', 'Anglais'),
('decorate', 'Anglais'),
('decoration', 'Anglais'),
('decorative', 'Anglais'),
('decrease', 'Anglais'),
('deep', 'Anglais'),
('deeply', 'Anglais'),
('defeat', 'Anglais'),
('defence', 'Anglais'),
('defend', 'Anglais'),
('define', 'Anglais'),
('definite', 'Anglais'),
('definitely', 'Anglais'),
('definition', 'Anglais'),
('degree', 'Anglais'),
('delay', 'Anglais'),
('deliberate', 'Anglais'),
('deliberately', 'Anglais'),
('delicate', 'Anglais'),
('delight', 'Anglais'),
('delighted', 'Anglais'),
('deliver', 'Anglais'),
('delivery', 'Anglais'),
('demand', 'Anglais'),
('demonstrate', 'Anglais'),
('dentist', 'Anglais'),
('deny', 'Anglais'),
('department', 'Anglais'),
('departure', 'Anglais'),
('depend', 'Anglais'),
('depend on', 'Anglais'),
('deposit', 'Anglais'),
('depress', 'Anglais'),
('depressed', 'Anglais'),
('depressing', 'Anglais'),
('depth', 'Anglais'),
('derive', 'Anglais'),
('derive from', 'Anglais'),
('describe', 'Anglais'),
('description', 'Anglais'),
('desert', 'Anglais'),
('desert', 'Anglais'),
('deserted', 'Anglais'),
('deserve', 'Anglais'),
('design', 'Anglais'),
('desire', 'Anglais'),
('desk', 'Anglais'),
('desperate', 'Anglais'),
('desperately', 'Anglais'),
('despite', 'Anglais'),
('destroy', 'Anglais'),
('destruction', 'Anglais'),
('detail', 'Anglais'),
('detailed', 'Anglais'),
('determination', 'Anglais'),
('determine', 'Anglais'),
('determined', 'Anglais'),
('develop', 'Anglais'),
('development', 'Anglais'),
('device', 'Anglais'),
('devote', 'Anglais'),
('devoted', 'Anglais'),
('devote to', 'Anglais'),
('diagram', 'Anglais'),
('diamond', 'Anglais'),
('diary', 'Anglais'),
('dictionary', 'Anglais'),
('die', 'Anglais'),
('die away', 'Anglais'),
('die out', 'Anglais'),
('diet', 'Anglais'),
('difference', 'Anglais'),
('different', 'Anglais'),
('differently', 'Anglais'),
('difficult', 'Anglais'),
('difficulty', 'Anglais'),
('dig', 'Anglais'),
('digital', 'Anglais'),
('dinner', 'Anglais'),
('direct', 'Anglais'),
('direction', 'Anglais'),
('directly', 'Anglais'),
('director', 'Anglais'),
('dirt', 'Anglais'),
('dirty', 'Anglais'),
('disabled', 'Anglais'),
('disadvantage', 'Anglais'),
('disagree', 'Anglais'),
('disagreement', 'Anglais'),
('disagree with doing', 'Anglais'),
('disappear', 'Anglais'),
('disappoint', 'Anglais'),
('disappointed', 'Anglais'),
('disappointing', 'Anglais'),
('disappointment', 'Anglais'),
('disapproval', 'Anglais'),
('disapprove', 'Anglais'),
('disapproving', 'Anglais'),
('disaster', 'Anglais'),
('disc', 'Anglais'),
('discipline', 'Anglais'),
('discount', 'Anglais'),
('discover', 'Anglais'),
('discovery', 'Anglais'),
('discuss', 'Anglais'),
('discussion', 'Anglais'),
('disease', 'Anglais'),
('disgust', 'Anglais'),
('disgusted', 'Anglais'),
('disgusting', 'Anglais'),
('dish', 'Anglais'),
('dishonest', 'Anglais'),
('dishonestly', 'Anglais'),
('disk', 'Anglais'),
('dislike', 'Anglais'),
('dismiss', 'Anglais'),
('display', 'Anglais'),
('dissolve', 'Anglais'),
('distance', 'Anglais'),
('distinguish', 'Anglais'),
('distribute', 'Anglais'),
('distribution', 'Anglais'),
('district', 'Anglais'),
('disturb', 'Anglais'),
('disturbing', 'Anglais'),
('divide', 'Anglais'),
('division', 'Anglais'),
('divorce', 'Anglais'),
('divorced', 'Anglais'),
('do 1', 'Anglais'),
('doctor', 'Anglais'),
('document', 'Anglais'),
('dog', 'Anglais'),
('dollar', 'Anglais'),
('domestic', 'Anglais'),
('dominate', 'Anglais'),
('door', 'Anglais'),
('dot', 'Anglais'),
('double', 'Anglais'),
('doubt', 'Anglais'),
('do up', 'Anglais'),
('do with', 'Anglais'),
('do without', 'Anglais'),
('down', 'Anglais'),
('downstairs', 'Anglais'),
('downward', 'Anglais'),
('downwards', 'Anglais'),
('dozen', 'Anglais'),
('draft', 'Anglais'),
('drag', 'Anglais'),
('drama', 'Anglais'),
('dramatic', 'Anglais'),
('dramatically', 'Anglais'),
('draw', 'Anglais'),
('drawer', 'Anglais'),
('drawing', 'Anglais'),
('dream', 'Anglais'),
('dress', 'Anglais'),
('dressed', 'Anglais'),
('dress up', 'Anglais'),
('drink', 'Anglais'),
('drive', 'Anglais'),
('drive away', 'Anglais'),
('drive off', 'Anglais'),
('driver', 'Anglais'),
('driving', 'Anglais'),
('drop', 'Anglais'),
('drop out', 'Anglais'),
('drug', 'Anglais'),
('drugstore', 'Anglais'),
('drum', 'Anglais'),
('drunk', 'Anglais'),
('dry', 'Anglais'),
('dry off', 'Anglais'),
('dry up', 'Anglais'),
('due', 'Anglais'),
('dull', 'Anglais'),
('dump', 'Anglais'),
('during', 'Anglais'),
('dust', 'Anglais'),
('duty', 'Anglais'),
('DVD', 'Anglais'),
('dying', 'Anglais'),
('each', 'Anglais'),
('each other', 'Anglais'),
('ear', 'Anglais'),
('early', 'Anglais'),
('earn', 'Anglais'),
('earth', 'Anglais'),
('ease', 'Anglais'),
('easily', 'Anglais'),
('east', 'Anglais'),
('eastern', 'Anglais'),
('easy', 'Anglais'),
('eat', 'Anglais'),
('eat out', 'Anglais'),
('eat up', 'Anglais'),
('economic', 'Anglais'),
('economy', 'Anglais'),
('edge', 'Anglais'),
('edition', 'Anglais'),
('editor', 'Anglais'),
('educate', 'Anglais'),
('educated', 'Anglais'),
('education', 'Anglais'),
('effect', 'Anglais'),
('effective', 'Anglais'),
('effectively', 'Anglais'),
('efficient', 'Anglais'),
('efficiently', 'Anglais'),
('effort', 'Anglais'),
('e.g.', 'Anglais'),
('egg', 'Anglais'),
('eight', 'Anglais'),
('eighteen', 'Anglais'),
('eighteenth', 'Anglais'),
('eighth', 'Anglais'),
('eightieth', 'Anglais'),
('eighty', 'Anglais'),
('either', 'Anglais'),
('elbow', 'Anglais'),
('elderly', 'Anglais'),
('elect', 'Anglais'),
('election', 'Anglais'),
('electric', 'Anglais'),
('electrical', 'Anglais'),
('electricity', 'Anglais'),
('electronic', 'Anglais'),
('elegant', 'Anglais'),
('element', 'Anglais'),
('elevator', 'Anglais'),
('eleven', 'Anglais'),
('eleventh', 'Anglais'),
('else', 'Anglais'),
('elsewhere', 'Anglais'),
('email', 'Anglais'),
('embarrass', 'Anglais'),
('embarrassed', 'Anglais'),
('embarrassing', 'Anglais'),
('embarrassment', 'Anglais'),
('emerge', 'Anglais'),
('emergency', 'Anglais'),
('emotion', 'Anglais'),
('emotional', 'Anglais'),
('emotionally', 'Anglais'),
('emphasis', 'Anglais'),
('emphasize', 'Anglais'),
('empire', 'Anglais'),
('employ', 'Anglais'),
('employee', 'Anglais'),
('employer', 'Anglais'),
('employment', 'Anglais'),
('empty', 'Anglais'),
('enable', 'Anglais'),
('encounter', 'Anglais'),
('encourage', 'Anglais'),
('encouragement', 'Anglais'),
('end', 'Anglais'),
('end in', 'Anglais'),
('ending', 'Anglais'),
('end up', 'Anglais'),
('enemy', 'Anglais'),
('energy', 'Anglais'),
('engage', 'Anglais'),
('engaged', 'Anglais'),
('engine', 'Anglais'),
('engineer', 'Anglais'),
('engineering', 'Anglais'),
('enjoy', 'Anglais'),
('enjoyable', 'Anglais'),
('enjoyment', 'Anglais'),
('enormous', 'Anglais'),
('enough', 'Anglais'),
('enquiry', 'Anglais'),
('ensure', 'Anglais'),
('enter', 'Anglais'),
('entertain', 'Anglais'),
('entertainer', 'Anglais'),
('entertaining', 'Anglais'),
('entertainment', 'Anglais'),
('enthusiasm', 'Anglais'),
('enthusiastic', 'Anglais'),
('enthusiastically', 'Anglais'),
('entire', 'Anglais'),
('entirely', 'Anglais'),
('entitle', 'Anglais'),
('entrance', 'Anglais'),
('entry', 'Anglais'),
('envelope', 'Anglais'),
('environment', 'Anglais'),
('environmental', 'Anglais'),
('equal', 'Anglais'),
('equally', 'Anglais'),
('equipment', 'Anglais'),
('equivalent', 'Anglais'),
('error', 'Anglais'),
('escape', 'Anglais'),
('especially', 'Anglais'),
('essay', 'Anglais'),
('essential', 'Anglais'),
('essentially', 'Anglais'),
('establish', 'Anglais'),
('estate', 'Anglais'),
('estimate', 'Anglais'),
('etc.', 'Anglais'),
('euro', 'Anglais'),
('even', 'Anglais'),
('evening', 'Anglais'),
('event', 'Anglais'),
('eventually', 'Anglais'),
('ever', 'Anglais'),
('every', 'Anglais'),
('everybody', 'Anglais'),
('everyone', 'Anglais'),
('everything', 'Anglais'),
('everywhere', 'Anglais'),
('evidence', 'Anglais'),
('evil', 'Anglais'),
('ex-', 'Anglais'),
('exact', 'Anglais'),
('exactly', 'Anglais'),
('exaggerate', 'Anglais'),
('exaggerated', 'Anglais'),
('exam', 'Anglais'),
('examination', 'Anglais'),
('examine', 'Anglais'),
('example', 'Anglais'),
('excellent', 'Anglais'),
('except', 'Anglais'),
('exception', 'Anglais'),
('exchange', 'Anglais'),
('excite', 'Anglais'),
('excited', 'Anglais'),
('excitement', 'Anglais'),
('exciting', 'Anglais'),
('exclude', 'Anglais'),
('excluding', 'Anglais'),
('excuse', 'Anglais'),
('excuse', 'Anglais'),
('executive', 'Anglais'),
('exercise', 'Anglais'),
('exhibit', 'Anglais'),
('exhibition', 'Anglais'),
('exist', 'Anglais'),
('existence', 'Anglais'),
('exit', 'Anglais'),
('expand', 'Anglais'),
('expect', 'Anglais'),
('expectation', 'Anglais'),
('expected', 'Anglais'),
('expense', 'Anglais'),
('expensive', 'Anglais'),
('experience', 'Anglais'),
('experienced', 'Anglais'),
('experiment', 'Anglais'),
('expert', 'Anglais'),
('explain', 'Anglais'),
('explanation', 'Anglais'),
('explode', 'Anglais'),
('explore', 'Anglais'),
('explosion', 'Anglais'),
('export', 'Anglais'),
('export', 'Anglais'),
('expose', 'Anglais'),
('express', 'Anglais'),
('expression', 'Anglais'),
('extend', 'Anglais'),
('extension', 'Anglais'),
('extensive', 'Anglais'),
('extent', 'Anglais'),
('extra', 'Anglais'),
('extraordinary', 'Anglais'),
('extreme', 'Anglais'),
('extremely', 'Anglais'),
('eye', 'Anglais'),
('face', 'Anglais'),
('face up to', 'Anglais'),
('facility', 'Anglais'),
('fact', 'Anglais'),
('factor', 'Anglais'),
('factory', 'Anglais'),
('fail', 'Anglais'),
('failure', 'Anglais'),
('faint', 'Anglais'),
('faintly', 'Anglais'),
('fair', 'Anglais'),
('fairly', 'Anglais'),
('faith', 'Anglais'),
('faithful', 'Anglais'),
('faithfully', 'Anglais'),
('fall', 'Anglais'),
('false', 'Anglais'),
('fame', 'Anglais'),
('familiar', 'Anglais'),
('family', 'Anglais'),
('famous', 'Anglais'),
('fan', 'Anglais'),
('fancy', 'Anglais'),
('far', 'Anglais'),
('farm', 'Anglais'),
('farmer', 'Anglais'),
('farming', 'Anglais'),
('farther', 'Anglais'),
('farthest', 'Anglais'),
('fashion', 'Anglais'),
('fashionable', 'Anglais'),
('fast', 'Anglais'),
('fasten', 'Anglais'),
('fat', 'Anglais'),
('father', 'Anglais'),
('faucet', 'Anglais'),
('fault', 'Anglais'),
('favour', 'Anglais'),
('favourite', 'Anglais'),
('fear', 'Anglais'),
('feather', 'Anglais'),
('feature', 'Anglais'),
('February', 'Anglais'),
('federal', 'Anglais'),
('fee', 'Anglais'),
('feed', 'Anglais'),
('feel', 'Anglais'),
('feeling', 'Anglais'),
('fellow', 'Anglais'),
('female', 'Anglais'),
('fence', 'Anglais'),
('festival', 'Anglais'),
('fetch', 'Anglais'),
('fever', 'Anglais'),
('few', 'Anglais'),
('field', 'Anglais'),
('fifteen', 'Anglais'),
('fifteenth', 'Anglais'),
('fifth', 'Anglais'),
('fiftieth', 'Anglais'),
('fifty', 'Anglais'),
('fight', 'Anglais'),
('fighting', 'Anglais'),
('figure', 'Anglais'),
('figure out', 'Anglais'),
('file', 'Anglais'),
('fill', 'Anglais'),
('fill in', 'Anglais'),
('fill out', 'Anglais'),
('fill up', 'Anglais'),
('film', 'Anglais'),
('final', 'Anglais'),
('finally', 'Anglais'),
('finance', 'Anglais'),
('financial', 'Anglais'),
('find', 'Anglais'),
('find out', 'Anglais'),
('fine', 'Anglais'),
('finely', 'Anglais'),
('finger', 'Anglais'),
('finish', 'Anglais'),
('finished', 'Anglais'),
('finish off', 'Anglais'),
('fire', 'Anglais'),
('firm', 'Anglais'),
('firmly', 'Anglais'),
('first', 'Anglais'),
('fish', 'Anglais'),
('fishing', 'Anglais'),
('fit', 'Anglais'),
('fit in', 'Anglais'),
('five', 'Anglais'),
('fix', 'Anglais'),
('fixed', 'Anglais'),
('flag', 'Anglais'),
('flame', 'Anglais'),
('flash', 'Anglais'),
('flat', 'Anglais'),
('flavour', 'Anglais'),
('flesh', 'Anglais'),
('flight', 'Anglais'),
('float', 'Anglais'),
('flood', 'Anglais'),
('flooded', 'Anglais'),
('flooding', 'Anglais'),
('floor', 'Anglais'),
('flour', 'Anglais'),
('flow', 'Anglais'),
('flower', 'Anglais'),
('flu', 'Anglais'),
('fly', 'Anglais'),
('flying', 'Anglais'),
('focus', 'Anglais'),
('fold', 'Anglais'),
('folding', 'Anglais'),
('follow', 'Anglais'),
('following', 'Anglais'),
('follow up', 'Anglais'),
('food', 'Anglais'),
('foot', 'Anglais'),
('football', 'Anglais'),
('for', 'Anglais'),
('force', 'Anglais'),
('forecast', 'Anglais'),
('foreign', 'Anglais'),
('forest', 'Anglais'),
('forever', 'Anglais'),
('forget', 'Anglais'),
('forgive', 'Anglais'),
('fork', 'Anglais'),
('form', 'Anglais'),
('formal', 'Anglais'),
('formally', 'Anglais'),
('former', 'Anglais'),
('formerly', 'Anglais'),
('formula', 'Anglais'),
('fortieth', 'Anglais'),
('fortune', 'Anglais'),
('forty', 'Anglais'),
('forward', 'Anglais'),
('found', 'Anglais'),
('foundation', 'Anglais'),
('four', 'Anglais'),
('fourteen', 'Anglais'),
('fourteenth', 'Anglais'),
('fourth', 'Anglais'),
('frame', 'Anglais'),
('free', 'Anglais'),
('freedom', 'Anglais'),
('freely', 'Anglais'),
('freeze', 'Anglais'),
('frequent', 'Anglais'),
('frequently', 'Anglais'),
('fresh', 'Anglais'),
('freshly', 'Anglais'),
('Friday', 'Anglais'),
('fridge', 'Anglais'),
('friend', 'Anglais'),
('friendly', 'Anglais'),
('friendship', 'Anglais'),
('frighten', 'Anglais'),
('frighten away/off', 'Anglais'),
('frightened', 'Anglais'),
('frightening', 'Anglais'),
('from', 'Anglais'),
('front', 'Anglais'),
('frozen', 'Anglais'),
('fruit', 'Anglais'),
('fry', 'Anglais'),
('fuel', 'Anglais'),
('full', 'Anglais'),
('fully', 'Anglais'),
('fun', 'Anglais'),
('function', 'Anglais'),
('function as', 'Anglais'),
('fund', 'Anglais'),
('fundamental', 'Anglais'),
('funeral', 'Anglais'),
('funny', 'Anglais'),
('fur', 'Anglais'),
('furniture', 'Anglais'),
('further', 'Anglais'),
('future', 'Anglais'),
('gain', 'Anglais'),
('gallon', 'Anglais'),
('gamble', 'Anglais'),
('gambling', 'Anglais'),
('game', 'Anglais'),
('gap', 'Anglais'),
('garage', 'Anglais'),
('garbage', 'Anglais'),
('garden', 'Anglais'),
('gas', 'Anglais'),
('gasoline', 'Anglais'),
('gate', 'Anglais'),
('gather', 'Anglais'),
('gear', 'Anglais'),
('general', 'Anglais'),
('generally', 'Anglais'),
('generate', 'Anglais'),
('generation', 'Anglais'),
('generous', 'Anglais'),
('generously', 'Anglais'),
('gentle', 'Anglais'),
('gentleman', 'Anglais'),
('gently', 'Anglais'),
('genuine', 'Anglais'),
('genuinely', 'Anglais'),
('flower', 'Anglais'),
('flu', 'Anglais'),
('fly', 'Anglais'),
('flying', 'Anglais'),
('focus', 'Anglais'),
('fold', 'Anglais'),
('folding', 'Anglais'),
('follow', 'Anglais'),
('following', 'Anglais'),
('follow up', 'Anglais'),
('food', 'Anglais'),
('foot', 'Anglais'),
('football', 'Anglais'),
('for', 'Anglais'),
('force', 'Anglais'),
('forecast', 'Anglais'),
('foreign', 'Anglais'),
('forest', 'Anglais'),
('forever', 'Anglais'),
('forget', 'Anglais'),
('forgive', 'Anglais'),
('fork', 'Anglais'),
('form', 'Anglais'),
('formal', 'Anglais'),
('formally', 'Anglais'),
('former', 'Anglais'),
('formerly', 'Anglais'),
('formula', 'Anglais'),
('fortieth', 'Anglais'),
('fortune', 'Anglais'),
('forty', 'Anglais'),
('forward', 'Anglais'),
('found', 'Anglais'),
('foundation', 'Anglais'),
('four', 'Anglais'),
('fourteen', 'Anglais'),
('fourteenth', 'Anglais'),
('fourth', 'Anglais'),
('frame', 'Anglais'),
('free', 'Anglais'),
('freedom', 'Anglais'),
('freely', 'Anglais'),
('freeze', 'Anglais'),
('frequent', 'Anglais'),
('frequently', 'Anglais'),
('fresh', 'Anglais'),
('freshly', 'Anglais'),
('Friday', 'Anglais'),
('fridge', 'Anglais'),
('friend', 'Anglais'),
('friendly', 'Anglais'),
('friendship', 'Anglais'),
('frighten', 'Anglais'),
('frighten away/off', 'Anglais'),
('frightened', 'Anglais'),
('frightening', 'Anglais'),
('from', 'Anglais'),
('front', 'Anglais'),
('frozen', 'Anglais'),
('fruit', 'Anglais'),
('fry', 'Anglais'),
('fuel', 'Anglais'),
('full', 'Anglais'),
('fully', 'Anglais'),
('fun', 'Anglais'),
('function', 'Anglais'),
('function as', 'Anglais'),
('fund', 'Anglais'),
('fundamental', 'Anglais'),
('funeral', 'Anglais'),
('funny', 'Anglais'),
('fur', 'Anglais'),
('furniture', 'Anglais'),
('further', 'Anglais'),
('future', 'Anglais'),
('gain', 'Anglais'),
('gallon', 'Anglais'),
('gamble', 'Anglais'),
('gambling', 'Anglais'),
('game', 'Anglais'),
('gap', 'Anglais'),
('garage', 'Anglais'),
('garbage', 'Anglais'),
('garden', 'Anglais'),
('gas', 'Anglais'),
('gasoline', 'Anglais'),
('gate', 'Anglais'),
('gather', 'Anglais'),
('gear', 'Anglais'),
('general', 'Anglais'),
('generally', 'Anglais'),
('generate', 'Anglais'),
('generation', 'Anglais'),
('generous', 'Anglais'),
('generously', 'Anglais'),
('gentle', 'Anglais'),
('gentleman', 'Anglais'),
('gently', 'Anglais'),
('genuine', 'Anglais'),
('genuinely', 'Anglais'),
('habit', 'Anglais'),
('hair', 'Anglais'),
('hairdresser', 'Anglais'),
('half', 'Anglais'),
('hall', 'Anglais'),
('hammer', 'Anglais'),
('hand', 'Anglais'),
('hand back', 'Anglais'),
('hand down', 'Anglais'),
('hand in', 'Anglais'),
('handle', 'Anglais'),
('hand out', 'Anglais'),
('hand over', 'Anglais'),
('hand round', 'Anglais'),
('hang', 'Anglais'),
('hang about', 'Anglais'),
('hang about with', 'Anglais'),
('hang around', 'Anglais'),
('hang around with', 'Anglais'),
('hang on', 'Anglais'),
('hang on to', 'Anglais'),
('hang up', 'Anglais'),
('happen', 'Anglais'),
('happen to', 'Anglais'),
('happily', 'Anglais'),
('happiness', 'Anglais'),
('happy', 'Anglais'),
('hard', 'Anglais'),
('hardly', 'Anglais'),
('harm', 'Anglais'),
('harmful', 'Anglais'),
('harmless', 'Anglais'),
('hat', 'Anglais'),
('hate', 'Anglais'),
('hatred', 'Anglais'),
('have', 'Anglais'),
('have back', 'Anglais'),
('have on', 'Anglais'),
('have to', 'Anglais'),
('he', 'Anglais'),
('head', 'Anglais'),
('headache', 'Anglais'),
('heal', 'Anglais'),
('health', 'Anglais'),
('healthy', 'Anglais'),
('hear', 'Anglais'),
('hear from', 'Anglais'),
('hearing', 'Anglais'),
('hear of', 'Anglais'),
('heart', 'Anglais'),
('heat', 'Anglais'),
('heating', 'Anglais'),
('heat up', 'Anglais'),
('heaven', 'Anglais'),
('heavily', 'Anglais'),
('heavy', 'Anglais'),
('heel', 'Anglais'),
('height', 'Anglais'),
('hell', 'Anglais'),
('hello', 'Anglais'),
('help', 'Anglais'),
('helpful', 'Anglais'),
('help out', 'Anglais'),
('hence', 'Anglais'),
('her', 'Anglais'),
('here', 'Anglais'),
('hero', 'Anglais'),
('hers', 'Anglais'),
('herself', 'Anglais'),
('hesitate', 'Anglais'),
('hi', 'Anglais'),
('hide', 'Anglais'),
('high', 'Anglais'),
('highlight', 'Anglais'),
('highly', 'Anglais'),
('highway', 'Anglais'),
('hill', 'Anglais'),
('him', 'Anglais'),
('himself', 'Anglais'),
('hip', 'Anglais'),
('hire', 'Anglais'),
('hire out', 'Anglais'),
('his', 'Anglais'),
('historical', 'Anglais'),
('history', 'Anglais'),
('hit', 'Anglais'),
('hobby', 'Anglais'),
('hold', 'Anglais'),
('hold back', 'Anglais'),
('hold on', 'Anglais'),
('hold on to', 'Anglais'),
('hold out', 'Anglais'),
('hold up', 'Anglais'),
('hole', 'Anglais'),
('holiday', 'Anglais'),
('hollow', 'Anglais'),
('holy', 'Anglais'),
('home', 'Anglais'),
('homework', 'Anglais'),
('honest', 'Anglais'),
('honestly', 'Anglais'),
('honour', 'Anglais'),
('hook', 'Anglais'),
('hope', 'Anglais'),
('horizontal', 'Anglais'),
('horn', 'Anglais'),
('horror', 'Anglais'),
('horse', 'Anglais'),
('hospital', 'Anglais'),
('host', 'Anglais'),
('hot', 'Anglais'),
('hotel', 'Anglais'),
('hour', 'Anglais'),
('house', 'Anglais'),
('household', 'Anglais'),
('housing', 'Anglais'),
('how', 'Anglais'),
('however', 'Anglais'),
('huge', 'Anglais'),
('human', 'Anglais'),
('humorous', 'Anglais'),
('humour', 'Anglais'),
('hundred', 'Anglais'),
('hundredth', 'Anglais'),
('hungry', 'Anglais'),
('hunt', 'Anglais'),
('hunting', 'Anglais'),
('hurry', 'Anglais'),
('hurry up', 'Anglais'),
('hurt', 'Anglais'),
('husband', 'Anglais'),
('I', 'Anglais'),
('ice', 'Anglais'),
('ice cream', 'Anglais'),
('idea', 'Anglais'),
('ideal', 'Anglais'),
('identify', 'Anglais'),
('identify with', 'Anglais'),
('identity', 'Anglais'),
('i.e.', 'Anglais'),
('if', 'Anglais'),
('ignore', 'Anglais'),
('ill', 'Anglais'),
('illegal', 'Anglais'),
('illegally', 'Anglais'),
('illness', 'Anglais'),
('illustrate', 'Anglais'),
('image', 'Anglais'),
('imaginary', 'Anglais'),
('imagination', 'Anglais'),
('imagine', 'Anglais'),
('immediate', 'Anglais'),
('immediately', 'Anglais'),
('immoral', 'Anglais'),
('impact', 'Anglais'),
('impatient', 'Anglais'),
('implication', 'Anglais'),
('imply', 'Anglais'),
('import', 'Anglais'),
('import', 'Anglais'),
('importance', 'Anglais'),
('important', 'Anglais'),
('importantly', 'Anglais'),
('impose', 'Anglais'),
('impossible', 'Anglais'),
('impress', 'Anglais'),
('impressed', 'Anglais'),
('impression', 'Anglais'),
('impressive', 'Anglais'),
('improve', 'Anglais'),
('improvement', 'Anglais'),
('in', 'Anglais'),
('inability', 'Anglais'),
('inch', 'Anglais'),
('incident', 'Anglais'),
('include', 'Anglais'),
('including', 'Anglais'),
('income', 'Anglais'),
('increase', 'Anglais'),
('increasingly', 'Anglais'),
('indeed', 'Anglais'),
('independence', 'Anglais'),
('independent', 'Anglais'),
('independently', 'Anglais'),
('index', 'Anglais'),
('indicate', 'Anglais'),
('indication', 'Anglais'),
('indirect', 'Anglais'),
('indirectly', 'Anglais'),
('individual', 'Anglais'),
('indoor', 'Anglais'),
('indoors', 'Anglais'),
('industrial', 'Anglais'),
('industry', 'Anglais'),
('inevitable', 'Anglais'),
('inevitably', 'Anglais'),
('infect', 'Anglais'),
('infected', 'Anglais'),
('infection', 'Anglais'),
('infectious', 'Anglais'),
('influence', 'Anglais'),
('inform', 'Anglais'),
('informal', 'Anglais'),
('information', 'Anglais'),
('ingredient', 'Anglais'),
('initial', 'Anglais'),
('initially', 'Anglais'),
('initiative', 'Anglais'),
('injure', 'Anglais'),
('injured', 'Anglais'),
('injury', 'Anglais'),
('ink', 'Anglais'),
('inner', 'Anglais'),
('innocent', 'Anglais'),
('insect', 'Anglais'),
('insert', 'Anglais'),
('inside', 'Anglais'),
('insist', 'Anglais'),
('insist on', 'Anglais'),
('insist on doing', 'Anglais'),
('install', 'Anglais'),
('instance', 'Anglais'),
('instead', 'Anglais'),
('instead of', 'Anglais'),
('institute', 'Anglais'),
('institution', 'Anglais'),
('instruction', 'Anglais'),
('instrument', 'Anglais'),
('insult', 'Anglais'),
('insulting', 'Anglais'),
('insurance', 'Anglais'),
('intelligence', 'Anglais'),
('intelligent', 'Anglais'),
('intend', 'Anglais'),
('intended', 'Anglais'),
('intention', 'Anglais'),
('interest', 'Anglais'),
('interested', 'Anglais'),
('interesting', 'Anglais'),
('interior', 'Anglais'),
('internal', 'Anglais'),
('international', 'Anglais'),
('Internet', 'Anglais'),
('interpret', 'Anglais'),
('interpretation', 'Anglais'),
('interrupt', 'Anglais'),
('interruption', 'Anglais'),
('interval', 'Anglais'),
('interview', 'Anglais'),
('into', 'Anglais'),
('introduce', 'Anglais'),
('introduction', 'Anglais'),
('invent', 'Anglais'),
('invention', 'Anglais'),
('invest', 'Anglais'),
('investigate', 'Anglais'),
('investigation', 'Anglais'),
('investment', 'Anglais'),
('invitation', 'Anglais'),
('invite', 'Anglais'),
('involve', 'Anglais'),
('involved', 'Anglais'),
('involvement', 'Anglais'),
('iron', 'Anglais'),
('irritate', 'Anglais'),
('irritated', 'Anglais'),
('irritating', 'Anglais'),
('island', 'Anglais'),
('issue', 'Anglais'),
('it', 'Anglais'),
('item', 'Anglais'),
('its', 'Anglais'),
('itself', 'Anglais'),
('jacket', 'Anglais'),
('jam', 'Anglais'),
('January', 'Anglais'),
('jealous', 'Anglais'),
('jeans', 'Anglais'),
('jelly', 'Anglais'),
('jewellery', 'Anglais'),
('job', 'Anglais'),
('join', 'Anglais'),
('join in', 'Anglais'),
('joint', 'Anglais'),
('jointly', 'Anglais'),
('joke', 'Anglais'),
('journalist', 'Anglais'),
('journey', 'Anglais'),
('joy', 'Anglais'),
('judge', 'Anglais'),
('judgement', 'Anglais'),
('juice', 'Anglais'),
('July', 'Anglais'),
('jump', 'Anglais'),
('June', 'Anglais'),
('junior', 'Anglais'),
('just', 'Anglais'),
('justice', 'Anglais'),
('justified', 'Anglais'),
('justify', 'Anglais'),
('keen', 'Anglais'),
('keep', 'Anglais'),
('keep out', 'Anglais'),
('keep out of', 'Anglais'),
('keep up', 'Anglais'),
('keep up with', 'Anglais'),
('key', 'Anglais'),
('keyboard', 'Anglais'),
('kick', 'Anglais'),
('kid', 'Anglais'),
('kill', 'Anglais'),
('killing', 'Anglais'),
('kilogram', 'Anglais'),
('kilometre', 'Anglais'),
('kind', 'Anglais'),
('kindly', 'Anglais'),
('kindness', 'Anglais'),
('king', 'Anglais'),
('kiss', 'Anglais'),
('kitchen', 'Anglais'),
('knee', 'Anglais'),
('knife', 'Anglais'),
('knit', 'Anglais'),
('knitted', 'Anglais'),
('knitting', 'Anglais'),
('knock', 'Anglais'),
('knock down', 'Anglais'),
('knock out', 'Anglais'),
('knot', 'Anglais'),
('know', 'Anglais'),
('knowledge', 'Anglais'),
('lab', 'Anglais'),
('label', 'Anglais'),
('laboratory', 'Anglais'),
('labour', 'Anglais'),
('lack', 'Anglais'),
('lacking', 'Anglais'),
('lady', 'Anglais'),
('lake', 'Anglais'),
('lamp', 'Anglais'),
('land', 'Anglais'),
('landscape', 'Anglais'),
('lane', 'Anglais'),
('language', 'Anglais'),
('large', 'Anglais'),
('largely', 'Anglais'),
('last 1', 'Anglais'),
('late', 'Anglais'),
('later', 'Anglais'),
('latest', 'Anglais'),
('latter', 'Anglais'),
('laugh', 'Anglais'),
('laugh at', 'Anglais'),
('launch', 'Anglais'),
('law', 'Anglais'),
('lawyer', 'Anglais'),
('lay', 'Anglais'),
('layer', 'Anglais'),
('lazy', 'Anglais'),
('lead 1', 'Anglais'),
('leader', 'Anglais'),
('leading 1', 'Anglais'),
('leaf', 'Anglais'),
('league', 'Anglais'),
('lean', 'Anglais'),
('learn', 'Anglais'),
('least', 'Anglais'),
('leather', 'Anglais'),
('leave', 'Anglais'),
('leave out', 'Anglais'),
('lecture', 'Anglais'),
('left', 'Anglais'),
('leg', 'Anglais'),
('legal', 'Anglais'),
('legally', 'Anglais'),
('lemon', 'Anglais'),
('lend', 'Anglais'),
('length', 'Anglais'),
('less', 'Anglais'),
('lesson', 'Anglais'),
('let', 'Anglais'),
('let down', 'Anglais'),
('let off', 'Anglais'),
('letter', 'Anglais'),
('level', 'Anglais'),
('library', 'Anglais'),
('licence', 'Anglais'),
('license', 'Anglais'),
('lid', 'Anglais'),
('lie 1', 'Anglais'),
('lie 2', 'Anglais'),
('lie around', 'Anglais'),
('lie down', 'Anglais'),
('life', 'Anglais'),
('lift', 'Anglais'),
('light', 'Anglais'),
('lightly', 'Anglais'),
('like', 'Anglais'),
('likely', 'Anglais'),
('limit', 'Anglais'),
('limited', 'Anglais'),
('limit to', 'Anglais'),
('line', 'Anglais'),
('link', 'Anglais'),
('lip', 'Anglais'),
('liquid', 'Anglais'),
('list', 'Anglais'),
('listen', 'Anglais'),
('literature', 'Anglais'),
('litre', 'Anglais'),
('little', 'Anglais'),
('live 1', 'Anglais'),
('live 2', 'Anglais'),
('lively', 'Anglais'),
('live on', 'Anglais'),
('live through', 'Anglais'),
('live together', 'Anglais'),
('living', 'Anglais'),
('load', 'Anglais'),
('loan', 'Anglais'),
('local', 'Anglais'),
('locally', 'Anglais'),
('locate', 'Anglais'),
('located', 'Anglais'),
('location', 'Anglais'),
('lock', 'Anglais'),
('lock up', 'Anglais'),
('logic', 'Anglais'),
('logical', 'Anglais'),
('lonely', 'Anglais'),
('long', 'Anglais'),
('look', 'Anglais'),
('look after', 'Anglais'),
('look at', 'Anglais'),
('look down on', 'Anglais'),
('look forward to', 'Anglais'),
('look into', 'Anglais'),
('look on', 'Anglais'),
('look on with', 'Anglais'),
('look out', 'Anglais'),
('look out for', 'Anglais'),
('look round', 'Anglais'),
('look through', 'Anglais'),
('look up', 'Anglais'),
('look up to', 'Anglais'),
('loose', 'Anglais'),
('loosely', 'Anglais'),
('lord', 'Anglais'),
('lorry', 'Anglais'),
('lose', 'Anglais'),
('loss', 'Anglais'),
('lost', 'Anglais'),
('lot', 'Anglais'),
('loud', 'Anglais'),
('loudly', 'Anglais'),
('love', 'Anglais'),
('lovely', 'Anglais'),
('lover', 'Anglais'),
('low', 'Anglais'),
('loyal', 'Anglais'),
('luck', 'Anglais'),
('lucky', 'Anglais'),
('luggage', 'Anglais'),
('lump', 'Anglais'),
('lunch', 'Anglais'),
('lung', 'Anglais'),
('machine', 'Anglais'),
('machinery', 'Anglais'),
('mad', 'Anglais'),
('magazine', 'Anglais'),
('magic', 'Anglais'),
('mail', 'Anglais'),
('main', 'Anglais'),
('mainly', 'Anglais'),
('maintain', 'Anglais'),
('major', 'Anglais'),
('majority', 'Anglais'),
('make', 'Anglais'),
('make into', 'Anglais'),
('make up', 'Anglais'),
('make-up', 'Anglais'),
('make up for', 'Anglais'),
('male', 'Anglais'),
('mall', 'Anglais'),
('man', 'Anglais'),
('manage', 'Anglais'),
('management', 'Anglais'),
('manager', 'Anglais'),
('manner', 'Anglais'),
('manufacture', 'Anglais'),
('manufacturer', 'Anglais'),
('manufacturing', 'Anglais'),
('many', 'Anglais'),
('map', 'Anglais'),
('march', 'Anglais'),
('March', 'Anglais'),
('mark', 'Anglais'),
('market', 'Anglais'),
('marketing', 'Anglais'),
('marriage', 'Anglais'),
('married', 'Anglais'),
('marry', 'Anglais'),
('mass', 'Anglais'),
('massive', 'Anglais'),
('master', 'Anglais'),
('match', 'Anglais'),
('matching', 'Anglais'),
('match up', 'Anglais'),
('mate', 'Anglais'),
('material', 'Anglais'),
('mathematics', 'Anglais'),
('matter', 'Anglais'),
('maximum', 'Anglais'),
('may', 'Anglais'),
('May', 'Anglais'),
('maybe', 'Anglais'),
('mayor', 'Anglais'),
('me', 'Anglais'),
('meal', 'Anglais'),
('mean', 'Anglais'),
('meaning', 'Anglais'),
('means', 'Anglais'),
('meanwhile', 'Anglais'),
('measure', 'Anglais'),
('measurement', 'Anglais'),
('meat', 'Anglais'),
('media', 'Anglais'),
('medical', 'Anglais'),
('medicine', 'Anglais'),
('medium', 'Anglais'),
('meet', 'Anglais'),
('meeting', 'Anglais'),
('meet up', 'Anglais'),
('meet with', 'Anglais'),
('melt', 'Anglais'),
('member', 'Anglais'),
('membership', 'Anglais'),
('memory', 'Anglais'),
('mental', 'Anglais'),
('mentally', 'Anglais'),
('mention', 'Anglais'),
('menu', 'Anglais'),
('mere', 'Anglais'),
('merely', 'Anglais'),
('mess', 'Anglais'),
('message', 'Anglais'),
('metal', 'Anglais'),
('method', 'Anglais'),
('metre', 'Anglais'),
('mid-', 'Anglais'),
('midday', 'Anglais'),
('middle', 'Anglais'),
('midnight', 'Anglais'),
('might', 'Anglais'),
('mild', 'Anglais'),
('mile', 'Anglais'),
('military', 'Anglais'),
('milk', 'Anglais'),
('milligram', 'Anglais'),
('millimetre', 'Anglais'),
('million', 'Anglais'),
('millionth', 'Anglais'),
('mind', 'Anglais'),
('mine', 'Anglais'),
('mineral', 'Anglais'),
('minimum', 'Anglais'),
('minister', 'Anglais'),
('ministry', 'Anglais'),
('minor', 'Anglais'),
('minority', 'Anglais'),
('minute 1', 'Anglais'),
('mirror', 'Anglais'),
('miss', 'Anglais'),
('missing', 'Anglais'),
('miss out', 'Anglais'),
('mistake', 'Anglais'),
('mistake for', 'Anglais'),
('mistaken', 'Anglais'),
('mix', 'Anglais'),
('mixed', 'Anglais'),
('mixture', 'Anglais'),
('mix up', 'Anglais'),
('mobile', 'Anglais'),
('mobile phone', 'Anglais'),
('model', 'Anglais'),
('modern', 'Anglais'),
('mom', 'Anglais'),
('moment', 'Anglais'),
('Monday', 'Anglais'),
('money', 'Anglais'),
('monitor', 'Anglais'),
('month', 'Anglais'),
('mood', 'Anglais'),
('moon', 'Anglais'),
('moral', 'Anglais'),
('morally', 'Anglais'),
('more', 'Anglais'),
('moreover', 'Anglais'),
('morning', 'Anglais'),
('most', 'Anglais'),
('mostly', 'Anglais'),
('mother', 'Anglais'),
('motion', 'Anglais'),
('motor', 'Anglais'),
('motorbike', 'Anglais'),
('motorcycle', 'Anglais'),
('mount', 'Anglais'),
('mountain', 'Anglais'),
('mouse', 'Anglais'),
('mouth', 'Anglais'),
('move', 'Anglais'),
('move in', 'Anglais'),
('movement', 'Anglais'),
('move out', 'Anglais'),
('move over', 'Anglais'),
('movie', 'Anglais'),
('movie theater', 'Anglais'),
('moving', 'Anglais'),
('Mr', 'Anglais'),
('Mrs', 'Anglais'),
('Ms', 'Anglais'),
('much', 'Anglais'),
('mud', 'Anglais'),
('multiply', 'Anglais'),
('mum', 'Anglais'),
('murder', 'Anglais'),
('muscle', 'Anglais'),
('museum', 'Anglais'),
('music', 'Anglais'),
('musical', 'Anglais'),
('musician', 'Anglais'),
('must', 'Anglais'),
('my', 'Anglais'),
('myself', 'Anglais'),
('mysterious', 'Anglais'),
('mystery', 'Anglais'),
('nail', 'Anglais'),
('naked', 'Anglais'),
('name', 'Anglais'),
('narrow', 'Anglais'),
('nation', 'Anglais'),
('national', 'Anglais'),
('natural', 'Anglais'),
('naturally', 'Anglais'),
('nature', 'Anglais'),
('navy', 'Anglais'),
('near', 'Anglais'),
('nearby', 'Anglais'),
('nearly', 'Anglais'),
('neat', 'Anglais'),
('neatly', 'Anglais'),
('necessarily', 'Anglais'),
('necessary', 'Anglais'),
('neck', 'Anglais'),
('need', 'Anglais'),
('needle', 'Anglais'),
('negative', 'Anglais'),
('neighbour', 'Anglais'),
('neighbourhood', 'Anglais'),
('neither', 'Anglais'),
('nephew', 'Anglais'),
('nerve', 'Anglais'),
('nervous', 'Anglais'),
('nervously', 'Anglais'),
('nest', 'Anglais'),
('net', 'Anglais'),
('network', 'Anglais'),
('never', 'Anglais'),
('nevertheless', 'Anglais'),
('new', 'Anglais'),
('newly', 'Anglais'),
('news', 'Anglais'),
('newspaper', 'Anglais'),
('next', 'Anglais'),
('next to', 'Anglais'),
('nice', 'Anglais'),
('nicely', 'Anglais'),
('niece', 'Anglais'),
('night', 'Anglais'),
('nine', 'Anglais'),
('nineteen', 'Anglais'),
('nineteenth', 'Anglais'),
('ninetieth', 'Anglais'),
('ninety', 'Anglais'),
('ninth', 'Anglais'),
('no', 'Anglais'),
('nobody', 'Anglais'),
('noise', 'Anglais'),
('noisily', 'Anglais'),
('noisy', 'Anglais'),
('non-', 'Anglais'),
('none', 'Anglais'),
('nonsense', 'Anglais'),
('no one', 'Anglais'),
('nor', 'Anglais'),
('normal', 'Anglais'),
('normally', 'Anglais'),
('north', 'Anglais'),
('northern', 'Anglais'),
('nose', 'Anglais'),
('not', 'Anglais'),
('note', 'Anglais'),
('note down', 'Anglais'),
('nothing', 'Anglais'),
('notice', 'Anglais'),
('noticeable', 'Anglais'),
('novel', 'Anglais'),
('November', 'Anglais'),
('now', 'Anglais'),
('nowhere', 'Anglais'),
('nuclear', 'Anglais'),
('number', 'Anglais'),
('nurse', 'Anglais'),
('nut', 'Anglais'),
('obey', 'Anglais'),
('object', 'Anglais'),
('object', 'Anglais'),
('objective', 'Anglais'),
('observation', 'Anglais'),
('observe', 'Anglais'),
('obtain', 'Anglais'),
('obvious', 'Anglais'),
('obviously', 'Anglais'),
('occasion', 'Anglais'),
('occasionally', 'Anglais'),
('occupied', 'Anglais'),
('occupy', 'Anglais'),
('occur', 'Anglais'),
('occur to', 'Anglais'),
('ocean', 'Anglais'),
('o’clock', 'Anglais'),
('October', 'Anglais'),
('odd', 'Anglais'),
('oddly', 'Anglais'),
('of', 'Anglais'),
('off', 'Anglais'),
('offence', 'Anglais'),
('offend', 'Anglais'),
('offense', 'Anglais'),
('offensive', 'Anglais'),
('offer', 'Anglais'),
('office', 'Anglais'),
('officer', 'Anglais'),
('official', 'Anglais'),
('officially', 'Anglais'),
('often', 'Anglais'),
('oh', 'Anglais'),
('oil', 'Anglais'),
('OK', 'Anglais'),
('old', 'Anglais'),
('old-fashioned', 'Anglais'),
('on', 'Anglais'),
('once', 'Anglais'),
('one', 'Anglais'),
('one another', 'Anglais'),
('onion', 'Anglais'),
('online', 'Anglais'),
('only', 'Anglais'),
('onto', 'Anglais'),
('open', 'Anglais'),
('opening', 'Anglais'),
('openly', 'Anglais'),
('open up', 'Anglais'),
('operate', 'Anglais'),
('operation', 'Anglais'),
('opinion', 'Anglais'),
('opponent', 'Anglais'),
('opportunity', 'Anglais'),
('oppose', 'Anglais'),
('opposed', 'Anglais'),
('opposing', 'Anglais'),
('opposite', 'Anglais'),
('opposition', 'Anglais'),
('option', 'Anglais'),
('or', 'Anglais'),
('orange', 'Anglais'),
('order', 'Anglais'),
('ordinary', 'Anglais'),
('organ', 'Anglais'),
('organization', 'Anglais'),
('organize', 'Anglais'),
('organized', 'Anglais'),
('origin', 'Anglais'),
('original', 'Anglais'),
('originally', 'Anglais'),
('other', 'Anglais'),
('otherwise', 'Anglais'),
('ought to', 'Anglais'),
('our', 'Anglais'),
('ours', 'Anglais'),
('ourselves', 'Anglais'),
('out', 'Anglais'),
('outdoor', 'Anglais'),
('outdoors', 'Anglais'),
('outer', 'Anglais'),
('outline', 'Anglais'),
('output', 'Anglais'),
('outside', 'Anglais'),
('outside', 'Anglais'),
('outstanding', 'Anglais'),
('oven', 'Anglais'),
('over', 'Anglais'),
('overall', 'Anglais'),
('overall', 'Anglais'),
('overcome', 'Anglais'),
('owe', 'Anglais'),
('own', 'Anglais'),
('owner', 'Anglais'),
('own up', 'Anglais'),
('pace 1', 'Anglais'),
('pack', 'Anglais'),
('package', 'Anglais'),
('packaging', 'Anglais'),
('packet', 'Anglais'),
('pack up', 'Anglais'),
('page', 'Anglais'),
('pain', 'Anglais'),
('painful', 'Anglais'),
('paint', 'Anglais'),
('painter', 'Anglais'),
('painting', 'Anglais'),
('pair', 'Anglais'),
('palace', 'Anglais'),
('pale', 'Anglais'),
('pan', 'Anglais'),
 ('panel', 'Anglais'),
('pants', 'Anglais'),
('paper', 'Anglais'),
('parallel', 'Anglais'),
('parent', 'Anglais'),
('park', 'Anglais'),
('parliament', 'Anglais'),
('part', 'Anglais'),
('particular', 'Anglais'),
('particularly', 'Anglais'),
('partly', 'Anglais'),
('partner', 'Anglais'),
('partnership', 'Anglais'),
('party', 'Anglais'),
('pass', 'Anglais'),
('passage', 'Anglais'),
('pass away', 'Anglais'),
('pass by', 'Anglais'),
('passenger', 'Anglais'),
('passing', 'Anglais'),
('pass on', 'Anglais'),
('pass out', 'Anglais'),
('passport', 'Anglais'),
('pass round', 'Anglais'),
('pass through', 'Anglais'),
('past', 'Anglais'),
('path', 'Anglais'),
('patience', 'Anglais'),
('patient', 'Anglais'),
('pattern', 'Anglais'),
('pause', 'Anglais'),
('pay', 'Anglais'),
('pay back', 'Anglais'),
('payment', 'Anglais'),
('pay out', 'Anglais'),
('pay up', 'Anglais'),
('peace', 'Anglais'),
('peaceful', 'Anglais'),
('peak', 'Anglais'),
('pen', 'Anglais'),
('pencil', 'Anglais'),
('penny', 'Anglais'),
('pension 1', 'Anglais'),
('people', 'Anglais'),
('pepper', 'Anglais'),
('per', 'Anglais'),
('per cent', 'Anglais'),
('perfect', 'Anglais'),
('perfectly', 'Anglais'),
('perform', 'Anglais'),
('performance', 'Anglais'),
('performer', 'Anglais'),
('perhaps', 'Anglais'),
('period', 'Anglais'),
('permanent', 'Anglais'),
('permanently', 'Anglais'),
('permission', 'Anglais'),
('permit', 'Anglais'),
('person', 'Anglais'),
('personal', 'Anglais'),
('personality', 'Anglais'),
('personally', 'Anglais'),
('persuade', 'Anglais'),
('pet', 'Anglais'),
('petrol', 'Anglais'),
('phase', 'Anglais'),
('philosophy', 'Anglais'),
('phone', 'Anglais'),
('photo', 'Anglais'),
('photocopy', 'Anglais'),
('photograph', 'Anglais'),
('photographer', 'Anglais'),
('photography', 'Anglais'),
('phrase', 'Anglais'),
('physical', 'Anglais'),
('physically', 'Anglais'),
('physics', 'Anglais'),
('piano', 'Anglais'),
('pick', 'Anglais'),
('pick up', 'Anglais'),
('picture', 'Anglais'),
('piece', 'Anglais'),
('pig', 'Anglais'),
('pile', 'Anglais'),
('pile up', 'Anglais'),
('pill', 'Anglais'),
('pilot', 'Anglais'),
('pin', 'Anglais'),
('pink', 'Anglais'),
('pint', 'Anglais'),
('pipe', 'Anglais'),
('pitch', 'Anglais'),
('pity', 'Anglais'),
('place', 'Anglais'),
('plain', 'Anglais'),
('plan', 'Anglais'),
('plane', 'Anglais'),
('planet', 'Anglais'),
('planning', 'Anglais'),
('plant', 'Anglais'),
('plastic', 'Anglais'),
('plate', 'Anglais'),
('platform', 'Anglais'),
('play', 'Anglais'),
('play about', 'Anglais'),
('player', 'Anglais'),
('play with', 'Anglais'),
('pleasant', 'Anglais'),
('pleasantly', 'Anglais'),
('please', 'Anglais'),
('pleased', 'Anglais'),
('pleasing', 'Anglais'),
('pleasure', 'Anglais'),
('plenty', 'Anglais'),
('plot', 'Anglais'),
('plug', 'Anglais'),
('plug in', 'Anglais'),
('plus 1', 'Anglais'),
('p.m.', 'Anglais'),
('pocket', 'Anglais'),
('poem', 'Anglais'),
('poetry', 'Anglais'),
('point', 'Anglais'),
('pointed', 'Anglais'),
('point out', 'Anglais'),
('poison', 'Anglais'),
('poisonous', 'Anglais'),
('pole', 'Anglais'),
('police', 'Anglais'),
('policy', 'Anglais'),
('polish', 'Anglais'),
('polite', 'Anglais'),
('politely', 'Anglais'),
('political', 'Anglais'),
('politically', 'Anglais'),
('politician', 'Anglais'),
('politics', 'Anglais'),
('pollution', 'Anglais'),
('pool', 'Anglais'),
('poor', 'Anglais'),
('pop', 'Anglais'),
('popular', 'Anglais'),
('population', 'Anglais'),
('port', 'Anglais'),
('pose', 'Anglais'),
('position', 'Anglais'),
('positive', 'Anglais'),
('possess', 'Anglais'),
('possession', 'Anglais'),
('possibility', 'Anglais'),
('possible', 'Anglais'),
('possibly', 'Anglais'),
('post', 'Anglais'),
('post office', 'Anglais'),
('pot', 'Anglais'),
('potato', 'Anglais'),
('potential', 'Anglais'),
('potentially', 'Anglais'),
('pound', 'Anglais'),
('pour', 'Anglais'),
('powder', 'Anglais'),
('power', 'Anglais'),
('powerful', 'Anglais'),
('practical', 'Anglais'),
('practically', 'Anglais'),
('practice', 'Anglais'),
('practise', 'Anglais'),
('praise', 'Anglais'),
('pray', 'Anglais'),
('prayer', 'Anglais'),
('precise', 'Anglais'),
('precisely', 'Anglais'),
('predict', 'Anglais'),
('prefer', 'Anglais'),
('preference', 'Anglais'),
('pregnant', 'Anglais'),
('premises', 'Anglais'),
('preparation', 'Anglais'),
('prepare', 'Anglais'),
('prepared', 'Anglais'),
('presence', 'Anglais'),
('present', 'Anglais'),
('present', 'Anglais'),
('presentation', 'Anglais'),
('preserve', 'Anglais'),
('president', 'Anglais'),
('press', 'Anglais'),
('pressure', 'Anglais'),
('presumably', 'Anglais'),
('pretend', 'Anglais'),
('pretty', 'Anglais'),
('prevent', 'Anglais'),
('previous', 'Anglais'),
('previously', 'Anglais'),
('price', 'Anglais'),
('pride', 'Anglais'),
('priest', 'Anglais'),
('primarily', 'Anglais'),
('primary', 'Anglais'),
('prime minister', 'Anglais'),
('prince', 'Anglais'),
('princess', 'Anglais'),
('principle', 'Anglais'),
('print', 'Anglais'),
('printer', 'Anglais'),
('printing', 'Anglais'),
('print off', 'Anglais'),
('prior', 'Anglais'),
('priority', 'Anglais'),
('prison', 'Anglais'),
('prisoner', 'Anglais'),
('private', 'Anglais'),
('privately', 'Anglais'),
('prize', 'Anglais'),
('probable', 'Anglais'),
('probably', 'Anglais'),
('problem', 'Anglais'),
('procedure', 'Anglais'),
('proceed', 'Anglais'),
('process 1', 'Anglais'),
('produce', 'Anglais'),
('producer', 'Anglais'),
('product', 'Anglais'),
('production', 'Anglais'),
('profession', 'Anglais'),
('professional', 'Anglais'),
('professor', 'Anglais'),
('profit', 'Anglais'),
('program', 'Anglais'),
('programme', 'Anglais'),
('progress', 'Anglais'),
('progress', 'Anglais'),
('project', 'Anglais'),
('project', 'Anglais'),
('promise', 'Anglais'),
('promote', 'Anglais'),
('promotion', 'Anglais'),
('prompt', 'Anglais'),
('promptly', 'Anglais'),
('pronounce', 'Anglais'),
('pronunciation', 'Anglais'),
('proof', 'Anglais'),
('proper', 'Anglais'),
('properly', 'Anglais'),
('property', 'Anglais'),
('proportion', 'Anglais'),
('proposal', 'Anglais'),
('propose', 'Anglais'),
('prospect', 'Anglais'),
('protect', 'Anglais'),
('protection', 'Anglais'),
('protest', 'Anglais'),
('protest', 'Anglais'),
('proud', 'Anglais'),
('proudly', 'Anglais'),
('prove', 'Anglais'),
('provide', 'Anglais'),
('provided', 'Anglais'),
('providing', 'Anglais'),
('pub', 'Anglais'),
('public', 'Anglais'),
('publication', 'Anglais'),
('publicity', 'Anglais'),
('publicly', 'Anglais'),
('publish', 'Anglais'),
('publishing', 'Anglais'),
('pull', 'Anglais'),
('pull apart', 'Anglais'),
('pull down', 'Anglais'),
('pull in', 'Anglais'),
('pull off', 'Anglais'),
('pull out', 'Anglais'),
('pull over', 'Anglais'),
('pull through', 'Anglais'),
('pull together', 'Anglais'),
('pull up', 'Anglais'),
('punch', 'Anglais'),
('punish', 'Anglais'),
('punishment', 'Anglais'),
('pupil', 'Anglais'),
('purchase', 'Anglais'),
('pure', 'Anglais'),
('purely', 'Anglais'),
('purple', 'Anglais'),
('purpose', 'Anglais'),
('pursue', 'Anglais'),
('push', 'Anglais'),
('push about', 'Anglais'),
('push forward', 'Anglais'),
('put', 'Anglais'),
('put away', 'Anglais'),
('put back', 'Anglais'),
('put down', 'Anglais'),
('put forward', 'Anglais'),
('put in', 'Anglais'),
('put off', 'Anglais'),
('put on', 'Anglais'),
('put out', 'Anglais'),
('put through', 'Anglais'),
('put together', 'Anglais'),
('put up', 'Anglais'),
('put up with', 'Anglais'),
('qualification', 'Anglais'),
('qualified', 'Anglais'),
('qualify', 'Anglais'),
('quality', 'Anglais'),
('quantity', 'Anglais'),
('quarter', 'Anglais'),
('queen', 'Anglais'),
('question', 'Anglais'),
('quick', 'Anglais'),
('quickly', 'Anglais'),
('quiet', 'Anglais'),
('quietly', 'Anglais'),
('quit', 'Anglais'),
('quite', 'Anglais'),
('quote', 'Anglais'),
('race', 'Anglais'),
('racing', 'Anglais'),
('radio', 'Anglais'),
('rail', 'Anglais'),
('railroad', 'Anglais'),
('railway', 'Anglais'),
('rain', 'Anglais'),
('raise', 'Anglais'),
('range', 'Anglais'),
('rank', 'Anglais'),
('rapid', 'Anglais'),
('rapidly', 'Anglais'),
('rare', 'Anglais'),
('rarely', 'Anglais'),
('rate', 'Anglais'),
('rather', 'Anglais'),
('raw', 'Anglais'),
('re-', 'Anglais'),
('reach', 'Anglais'),
('react', 'Anglais'),
('reaction', 'Anglais'),
('read', 'Anglais'),
('reader', 'Anglais'),
('reading', 'Anglais'),
('read out', 'Anglais'),
('read over', 'Anglais'),
('ready', 'Anglais'),
('real', 'Anglais'),
('realistic', 'Anglais'),
('reality', 'Anglais'),
('realize', 'Anglais'),
('really', 'Anglais'),
('rear', 'Anglais'),
('reason', 'Anglais'),
('reasonable', 'Anglais'),
('reasonably', 'Anglais'),
('recall', 'Anglais'),
('receipt', 'Anglais'),
('receive', 'Anglais'),
('recent', 'Anglais'),
('recently', 'Anglais'),
('reception', 'Anglais'),
('reckon', 'Anglais'),
('reckon on', 'Anglais'),
('recognition', 'Anglais'),
('recognize', 'Anglais'),
('recommend', 'Anglais'),
('record', 'Anglais'),
('record', 'Anglais'),
('recording', 'Anglais'),
('recover', 'Anglais'),
('red', 'Anglais'),
('reduce', 'Anglais'),
('reduction', 'Anglais'),
('refer', 'Anglais'),
('reference', 'Anglais'),
('refer to', 'Anglais'),
('reflect', 'Anglais'),
('reform', 'Anglais'),
('refrigerator', 'Anglais'),
('refusal', 'Anglais'),
('refuse', 'Anglais'),
 ('regard', 'Anglais'),
('regarding', 'Anglais'),
('region', 'Anglais'),
('regional', 'Anglais'),
('register', 'Anglais'),
('regret', 'Anglais'),
('regular', 'Anglais'),
('regularly', 'Anglais'),
('regulation', 'Anglais'),
('reject', 'Anglais'),
('relate', 'Anglais'),
('related', 'Anglais'),
('relate to', 'Anglais'),
('relation', 'Anglais'),
('relationship', 'Anglais'),
('relative', 'Anglais'),
('relatively', 'Anglais'),
('relax', 'Anglais'),
('relaxed', 'Anglais'),
('relaxing', 'Anglais'),
('release', 'Anglais'),
('relevant', 'Anglais'),
('relief', 'Anglais'),
('religion', 'Anglais'),
('religious', 'Anglais'),
('rely', 'Anglais'),
('rely on', 'Anglais'),
('remain', 'Anglais'),
('remaining', 'Anglais'),
('remains', 'Anglais'),
('remark', 'Anglais'),
('remarkable', 'Anglais'),
('remarkably', 'Anglais'),
('remember', 'Anglais'),
('remind', 'Anglais'),
('remind of', 'Anglais'),
('remote', 'Anglais'),
('removal', 'Anglais'),
('remove', 'Anglais'),
('rent', 'Anglais'),
('rented', 'Anglais'),
('repair', 'Anglais'),
('repeat', 'Anglais'),
('repeated', 'Anglais'),
('repeatedly', 'Anglais'),
('replace', 'Anglais'),
('reply', 'Anglais'),
('report', 'Anglais'),
('represent', 'Anglais'),
('representative', 'Anglais'),
('reproduce', 'Anglais'),
('reputation', 'Anglais'),
('request', 'Anglais'),
('require', 'Anglais'),
('requirement', 'Anglais'),
('rescue', 'Anglais'),
('research', 'Anglais'),
('reservation', 'Anglais'),
('reserve', 'Anglais'),
('resident', 'Anglais'),
('resist', 'Anglais'),
('resistance', 'Anglais'),
('resolve', 'Anglais'),
('resort', 'Anglais'),
('resort to', 'Anglais'),
('resource', 'Anglais'),
('respect', 'Anglais'),
('respond', 'Anglais'),
('response', 'Anglais'),
('responsibility', 'Anglais'),
('responsible', 'Anglais'),
('rest', 'Anglais'),
('restaurant', 'Anglais'),
('restore', 'Anglais'),
('restrict', 'Anglais'),
('restricted', 'Anglais'),
('restriction', 'Anglais'),
('result', 'Anglais'),
('result in', 'Anglais'),
('retain', 'Anglais'),
('retire', 'Anglais'),
('retired', 'Anglais'),
('retirement', 'Anglais'),
('return', 'Anglais'),
('reveal', 'Anglais'),
('reverse', 'Anglais'),
('review', 'Anglais'),
('revise', 'Anglais'),
('revision', 'Anglais'),
('revolution', 'Anglais'),
('reward', 'Anglais'),
('rhythm', 'Anglais'),
('rice', 'Anglais'),
('rich', 'Anglais'),
('rid', 'Anglais'),
('ride', 'Anglais'),
('rider', 'Anglais'),
('ridiculous', 'Anglais'),
('riding', 'Anglais'),
('right', 'Anglais'),
('rightly', 'Anglais'),
('ring 1', 'Anglais'),
('ring 2', 'Anglais'),
('ring back', 'Anglais'),
('rise', 'Anglais'),
('risk', 'Anglais'),
('rival', 'Anglais'),
('river', 'Anglais'),
('road', 'Anglais'),
('rob', 'Anglais'),
('rock', 'Anglais'),
('role', 'Anglais'),
('roll', 'Anglais'),
('romantic', 'Anglais'),
('roof', 'Anglais'),
('room', 'Anglais'),
('root', 'Anglais'),
('rope', 'Anglais'),
('rough', 'Anglais'),
('roughly', 'Anglais'),
('round', 'Anglais'),
('rounded', 'Anglais'),
('route', 'Anglais'),
('routine', 'Anglais'),
('row 1', 'Anglais'),
('royal', 'Anglais'),
('rub', 'Anglais'),
('rubber', 'Anglais'),
('rubbish', 'Anglais'),
('rude', 'Anglais'),
('rudely', 'Anglais'),
('ruin', 'Anglais'),
('ruined', 'Anglais'),
('rule', 'Anglais'),
('rule out', 'Anglais'),
('ruler', 'Anglais'),
('rumour', 'Anglais'),
('run', 'Anglais'),
('run after', 'Anglais'),
('run away', 'Anglais'),
('runner', 'Anglais'),
('running', 'Anglais'),
('run out', 'Anglais'),
('run over', 'Anglais'),
('run through', 'Anglais'),
('rural', 'Anglais'),
('rush', 'Anglais'),
('sack', 'Anglais'),
('sad', 'Anglais'),
('sadly', 'Anglais'),
('sadness', 'Anglais'),
('safe', 'Anglais'),
('safely', 'Anglais'),
('safety', 'Anglais'),
('sail', 'Anglais'),
('sailing', 'Anglais'),
('sailor', 'Anglais'),
('salad', 'Anglais'),
('salary', 'Anglais'),
('sale', 'Anglais'),
('salt', 'Anglais'),
('salty', 'Anglais'),
('same', 'Anglais'),
('sample', 'Anglais'),
('sand', 'Anglais'),
('satisfaction', 'Anglais'),
('satisfied', 'Anglais'),
('satisfy', 'Anglais'),
('satisfying', 'Anglais'),
('Saturday', 'Anglais'),
('sauce', 'Anglais'),
('save', 'Anglais'),
('saving', 'Anglais'),
('say', 'Anglais'),
('scale', 'Anglais'),
('scare', 'Anglais'),
('scared', 'Anglais'),
('scare off', 'Anglais'),
('scene', 'Anglais'),
('schedule', 'Anglais'),
('scheme', 'Anglais'),
('school', 'Anglais'),
('science', 'Anglais'),
('scientific', 'Anglais'),
('scientist', 'Anglais'),
('scissors', 'Anglais'),
('score', 'Anglais'),
('scratch', 'Anglais'),
('scream', 'Anglais'),
('screen', 'Anglais'),
('screw', 'Anglais'),
('sea', 'Anglais'),
('seal', 'Anglais'),
('seal off', 'Anglais'),
('search', 'Anglais'),
('season', 'Anglais'),
('seat', 'Anglais'),
('second 1', 'Anglais'),
('secondary', 'Anglais'),
('secret', 'Anglais'),
('secretary', 'Anglais'),
('secretly', 'Anglais'),
('section', 'Anglais'),
('sector', 'Anglais'),
('secure', 'Anglais'),
('security', 'Anglais'),
('see', 'Anglais'),
('see about', 'Anglais'),
('seed', 'Anglais'),
('seek', 'Anglais'),
('seem', 'Anglais'),
('see to', 'Anglais'),
('select', 'Anglais'),
('selection', 'Anglais'),
('self', 'Anglais'),
('self-', 'Anglais'),
('sell', 'Anglais'),
('sell off', 'Anglais'),
('sell out', 'Anglais'),
('senate', 'Anglais'),
('senator', 'Anglais'),
('send', 'Anglais'),
('send for', 'Anglais'),
('send off', 'Anglais'),
('senior', 'Anglais'),
('sense', 'Anglais'),
('sensible', 'Anglais'),
('sensitive', 'Anglais'),
('sentence', 'Anglais'),
('separate', 'Anglais'),
('separate', 'Anglais'),
('separated', 'Anglais'),
('separately', 'Anglais'),
('separation', 'Anglais'),
('September', 'Anglais'),
('series', 'Anglais'),
('serious', 'Anglais'),
('seriously', 'Anglais'),
('servant', 'Anglais'),
('serve', 'Anglais'),
('service', 'Anglais'),
('session', 'Anglais'),
('set', 'Anglais'),
('set off', 'Anglais'),
('set out', 'Anglais'),
('settle', 'Anglais'),
('settle down', 'Anglais'),
('set up', 'Anglais'),
('seven', 'Anglais'),
('seventeen', 'Anglais'),
('seventh', 'Anglais'),
('seventieth', 'Anglais'),
('seventy', 'Anglais'),
('several', 'Anglais'),
('severe', 'Anglais'),
('severely', 'Anglais'),
('sew', 'Anglais'),
('sewing', 'Anglais'),
('sex', 'Anglais'),
('sexual', 'Anglais'),
('sexually', 'Anglais'),
('shade', 'Anglais'),
('shadow', 'Anglais'),
('shake', 'Anglais'),
('shall', 'Anglais'),
('shallow', 'Anglais'),
('shame', 'Anglais'),
('shape', 'Anglais'),
('shaped', 'Anglais'),
('share', 'Anglais'),
('sharp', 'Anglais'),
('sharply', 'Anglais'),
('shave', 'Anglais'),
('she', 'Anglais'),
('sheep', 'Anglais'),
('sheet', 'Anglais'),
('shelf', 'Anglais'),
('shell', 'Anglais'),
('shelter', 'Anglais'),
('shift', 'Anglais'),
('shine', 'Anglais'),
('shiny', 'Anglais'),
('ship', 'Anglais'),
('shirt', 'Anglais'),
('shock', 'Anglais'),
('shocked', 'Anglais'),
('shocking', 'Anglais'),
('shoe', 'Anglais'),
('shoot', 'Anglais'),
('shoot down', 'Anglais'),
('shooting', 'Anglais'),
('shop', 'Anglais'),
('shopping', 'Anglais'),
('short', 'Anglais'),
('shortly', 'Anglais'),
('shot', 'Anglais'),
('should', 'Anglais'),
('shoulder', 'Anglais'),
('shout', 'Anglais'),
('show', 'Anglais'),
('shower', 'Anglais'),
('show off', 'Anglais'),
('show round', 'Anglais'),
('show up', 'Anglais'),
('shut', 'Anglais'),
('shut down', 'Anglais'),
('shut in', 'Anglais'),
('shut out', 'Anglais'),
('shut up', 'Anglais'),
('shy', 'Anglais'),
('sick', 'Anglais'),
('side', 'Anglais'),
('sideways', 'Anglais'),
('sight', 'Anglais'),
('sign', 'Anglais'),
('signal', 'Anglais'),
('signature', 'Anglais'),
('significant', 'Anglais'),
('significantly', 'Anglais'),
('silence', 'Anglais'),
('silent', 'Anglais'),
('silk', 'Anglais'),
('silly', 'Anglais'),
('silver', 'Anglais'),
('similar', 'Anglais'),
('similarly', 'Anglais'),
('simple', 'Anglais'),
('simply', 'Anglais'),
('since', 'Anglais'),
('sincere', 'Anglais'),
('sincerely', 'Anglais'),
('sing', 'Anglais'),
('singer', 'Anglais'),
('singing', 'Anglais'),
('single', 'Anglais'),
('sink', 'Anglais'),
('sir', 'Anglais'),
('sister', 'Anglais'),
('sit', 'Anglais'),
('sit down', 'Anglais'),
('site', 'Anglais'),
('situation', 'Anglais'),
('six', 'Anglais'),
('sixteen', 'Anglais'),
('sixth', 'Anglais'),
('sixtieth', 'Anglais'),
('sixty', 'Anglais'),
('size', 'Anglais'),
('skilful', 'Anglais'),
('skilfully', 'Anglais'),
('skill', 'Anglais'),
('skilled', 'Anglais'),
('skin', 'Anglais'),
('skirt', 'Anglais'),
('sky', 'Anglais'),
('sleep', 'Anglais'),
('sleeve', 'Anglais'),
('slice', 'Anglais'),
('slide', 'Anglais'),
('slight', 'Anglais'),
('slightly', 'Anglais'),
('slip', 'Anglais'),
('slope', 'Anglais'),
('slow', 'Anglais'),
('slowly', 'Anglais'),
('small', 'Anglais'),
('smart', 'Anglais'),
('smash', 'Anglais'),
('smell', 'Anglais'),
('smile', 'Anglais'),
('smoke', 'Anglais'),
('smoking', 'Anglais'),
('smooth', 'Anglais'),
('smoothly', 'Anglais'),
('snake', 'Anglais'),
('snow', 'Anglais'),
('so', 'Anglais'),
('soap', 'Anglais'),
('social', 'Anglais'),
('socially', 'Anglais'),
('society', 'Anglais'),
('sock', 'Anglais'),
('soft', 'Anglais'),
('softly', 'Anglais'),
('software', 'Anglais'),
('soil', 'Anglais'),
('soldier', 'Anglais'),
('solid', 'Anglais'),
('solution', 'Anglais'),
('solve', 'Anglais'),
('some', 'Anglais'),
('some', 'Anglais'),
('somebody', 'Anglais'),
('somehow', 'Anglais'),
('someone', 'Anglais'),
('something', 'Anglais'),
('sometimes', 'Anglais'),
('somewhat', 'Anglais'),
('somewhere', 'Anglais'),
('son', 'Anglais'),
('song', 'Anglais'),
('soon', 'Anglais'),
('sore', 'Anglais'),
('sorry', 'Anglais'),
('sort', 'Anglais'),
('sort out', 'Anglais'),
('soul', 'Anglais'),
('sound', 'Anglais'),
('soup', 'Anglais'),
('sour', 'Anglais'),
('source', 'Anglais'),
('south', 'Anglais'),
('southern', 'Anglais'),
('space', 'Anglais'),
('spare', 'Anglais'),
('speak', 'Anglais'),
('speaker', 'Anglais'),
('speak out', 'Anglais'),
('speak up', 'Anglais'),
('special', 'Anglais'),
('specialist', 'Anglais'),
('specially', 'Anglais'),
('specific', 'Anglais'),
('specifically', 'Anglais'),
('speech', 'Anglais'),
('speed', 'Anglais'),
('speed up', 'Anglais'),
('spell', 'Anglais'),
('spelling', 'Anglais'),
('spend', 'Anglais'),
('spice', 'Anglais'),
('spicy', 'Anglais'),
('spider', 'Anglais'),
('spin', 'Anglais'),
('spirit', 'Anglais'),
('spiritual', 'Anglais'),
('spite', 'Anglais'),
('split', 'Anglais'),
('split up', 'Anglais'),
('spoil', 'Anglais'),
('spoken', 'Anglais'),
('spoon', 'Anglais'),
('sport', 'Anglais'),
('spot', 'Anglais'),
('spray', 'Anglais'),
('spread', 'Anglais'),
('spread out', 'Anglais'),
('spring', 'Anglais'),
('square', 'Anglais'),
('squeeze', 'Anglais'),
('stable', 'Anglais'),
('staff', 'Anglais'),
('stage', 'Anglais'),
('stair', 'Anglais'),
('stamp', 'Anglais'),
('stand', 'Anglais'),
('standard', 'Anglais'),
('stand back', 'Anglais'),
('stand by', 'Anglais'),
('stand for', 'Anglais'),
('stand out', 'Anglais'),
('stand up', 'Anglais'),
('stand up for', 'Anglais'),
('star', 'Anglais'),
('stare', 'Anglais'),
('start', 'Anglais'),
('start off', 'Anglais'),
('start out', 'Anglais'),
('start up', 'Anglais'),
('state', 'Anglais'),
('statement', 'Anglais'),
('station', 'Anglais'),
('statue', 'Anglais'),
('status', 'Anglais'),
('stay', 'Anglais'),
('stay away', 'Anglais'),
('stay out of', 'Anglais'),
('steadily', 'Anglais'),
('steady', 'Anglais'),
('steal', 'Anglais'),
('steam', 'Anglais'),
('steel', 'Anglais'),
('steep', 'Anglais'),
('steeply', 'Anglais'),
('steer', 'Anglais'),
('step', 'Anglais'),
('stick', 'Anglais'),
('stick out', 'Anglais'),
('stick to', 'Anglais'),
('stick up', 'Anglais'),
('sticky', 'Anglais'),
('stiff', 'Anglais'),
('stiffly', 'Anglais'),
('still', 'Anglais'),
('sting', 'Anglais'),
('stir', 'Anglais'),
('stock', 'Anglais'),
('stomach', 'Anglais'),
('stone', 'Anglais'),
('stop', 'Anglais'),
('store', 'Anglais'),
('storm', 'Anglais'),
('story', 'Anglais'),
('stove', 'Anglais'),
('straight', 'Anglais'),
('strain', 'Anglais'),
('strange', 'Anglais'),
('strangely', 'Anglais'),
('stranger', 'Anglais'),
('strategy', 'Anglais'),
('stream', 'Anglais'),
('street', 'Anglais'),
('strength', 'Anglais'),
('stress', 'Anglais'),
('stressed', 'Anglais'),
('stretch', 'Anglais'),
('strict', 'Anglais'),
('strictly', 'Anglais'),
('strike', 'Anglais'),
('striking', 'Anglais'),
('string', 'Anglais'),
('strip', 'Anglais'),
('stripe', 'Anglais'),
('striped', 'Anglais'),
('stroke', 'Anglais'),
('strong', 'Anglais'),
('strongly', 'Anglais'),
('structure', 'Anglais'),
('struggle', 'Anglais'),
('student', 'Anglais'),
('studio', 'Anglais'),
('study', 'Anglais'),
('stuff', 'Anglais'),
('stupid', 'Anglais'),
('style', 'Anglais'),
('subject', 'Anglais'),
('substance', 'Anglais'),
('substantial', 'Anglais'),
('substantially', 'Anglais'),
('substitute', 'Anglais'),
('succeed', 'Anglais'),
('success', 'Anglais'),
('successful', 'Anglais'),
('successfully', 'Anglais'),
('such', 'Anglais'),
('suck', 'Anglais'),
('sudden', 'Anglais'),
('suddenly', 'Anglais'),
('suffer', 'Anglais'),
('suffering', 'Anglais'),
('sufficient', 'Anglais'),
('sufficiently', 'Anglais'),
('sugar', 'Anglais'),
('suggest', 'Anglais'),
('suggestion', 'Anglais'),
('suit', 'Anglais'),
('suitable', 'Anglais'),
('suitcase', 'Anglais'),
('suited', 'Anglais'),
('sum', 'Anglais'),
('summary', 'Anglais'),
('summer', 'Anglais'),
('sum up', 'Anglais'),
('sun', 'Anglais'),
('Sunday', 'Anglais'),
('superior', 'Anglais'),
('supermarket', 'Anglais'),
('supply', 'Anglais'),
('support', 'Anglais'),
('supporter', 'Anglais'),
('suppose', 'Anglais'),
('sure', 'Anglais'),
('surely', 'Anglais'),
('surface', 'Anglais'),
('surname', 'Anglais'),
('surprise', 'Anglais'),
('surprised', 'Anglais'),
('surprising', 'Anglais'),
('surprisingly', 'Anglais'),
('surround', 'Anglais'),
('surrounding', 'Anglais'),
('surroundings', 'Anglais'),
('survey', 'Anglais'),
('survey', 'Anglais'),
('survive', 'Anglais'),
('suspect', 'Anglais'),
('suspicion', 'Anglais'),
('suspicious', 'Anglais'),
('swallow', 'Anglais'),
('swear', 'Anglais'),
('swearing', 'Anglais'),
('sweat', 'Anglais'),
('sweater', 'Anglais'),
('sweep', 'Anglais'),
('sweet', 'Anglais'),
('swell', 'Anglais'),
('swelling', 'Anglais'),
('swim', 'Anglais'),
('swimming', 'Anglais'),
('swimming pool', 'Anglais'),
('swing', 'Anglais'),
('switch', 'Anglais'),
('switch off', 'Anglais'),
('swollen', 'Anglais'),
('symbol', 'Anglais'),
('sympathetic', 'Anglais'),
('sympathy', 'Anglais'),
('system', 'Anglais'),
('table', 'Anglais'),
('tablet', 'Anglais'),
('tackle', 'Anglais'),
('tail', 'Anglais'),
('take', 'Anglais'),
('take away', 'Anglais'),
('take back', 'Anglais'),
('take down', 'Anglais'),
('take in', 'Anglais'),
('take off', 'Anglais'),
('take on', 'Anglais'),
('take over', 'Anglais'),
('take up', 'Anglais'),
('talk', 'Anglais'),
('tall', 'Anglais'),
('tank', 'Anglais'),
('tap', 'Anglais'),
('tape', 'Anglais'),
('target', 'Anglais'),
('task', 'Anglais'),
('taste', 'Anglais'),
('tax', 'Anglais'),
('taxi', 'Anglais'),
('tea', 'Anglais'),
('teach', 'Anglais'),
('teacher', 'Anglais'),
('teaching', 'Anglais'),
('team', 'Anglais'),
('tear 1', 'Anglais'),
('tear 2', 'Anglais'),
('tear up', 'Anglais'),
('technical', 'Anglais'),
('technique', 'Anglais'),
('technology', 'Anglais'),
('telephone', 'Anglais'),
('television', 'Anglais'),
('tell', 'Anglais'),
('tell off', 'Anglais'),
('temperature', 'Anglais'),
('temporarily', 'Anglais'),
('temporary', 'Anglais'),
('ten', 'Anglais'),
('tend', 'Anglais'),
('tendency', 'Anglais'),
('tension', 'Anglais'),
('tent', 'Anglais'),
('tenth', 'Anglais'),
('term', 'Anglais'),
('terrible', 'Anglais'),
('terribly', 'Anglais'),
('test', 'Anglais'),
('text', 'Anglais'),
('than', 'Anglais'),
('thank', 'Anglais'),
('thanks', 'Anglais'),
('thank you', 'Anglais'),
('that', 'Anglais'),
('that', 'Anglais'),
('the', 'Anglais'),
('theatre', 'Anglais'),
('their', 'Anglais'),
('theirs', 'Anglais'),
('them', 'Anglais'),
('theme', 'Anglais'),
('themselves', 'Anglais'),
('then', 'Anglais'),
('theory', 'Anglais'),
('there', 'Anglais'),
('therefore', 'Anglais'),
('they', 'Anglais'),
('thick', 'Anglais'),
('thickly', 'Anglais'),
('thickness', 'Anglais'),
('thief', 'Anglais'),
('thin', 'Anglais'),
('thing', 'Anglais'),
('think', 'Anglais'),
('think about', 'Anglais'),
('thinking', 'Anglais'),
('think of', 'Anglais'),
('think of as', 'Anglais'),
('think over', 'Anglais'),
('think up', 'Anglais'),
('third', 'Anglais'),
('thirsty', 'Anglais'),
('thirteen', 'Anglais'),
('thirteenth', 'Anglais'),
('thirtieth', 'Anglais'),
('thirty', 'Anglais'),
('this', 'Anglais'),
('thorough', 'Anglais'),
('thoroughly', 'Anglais'),
('though', 'Anglais'),
('thought', 'Anglais'),
('thousand', 'Anglais'),
('thousandth', 'Anglais'),
('thread', 'Anglais'),
('threat', 'Anglais'),
('threaten', 'Anglais'),
('threatening', 'Anglais'),
('three', 'Anglais'),
('throat', 'Anglais'),
('through', 'Anglais'),
('throughout', 'Anglais'),
('throw', 'Anglais'),
('throw away', 'Anglais'),
('throw out', 'Anglais'),
('thumb', 'Anglais'),
('Thursday', 'Anglais'),
('thus', 'Anglais'),
('ticket', 'Anglais'),
('tidy', 'Anglais'),
('tie', 'Anglais'),
('tie up', 'Anglais'),
('tight', 'Anglais'),
('tightly', 'Anglais'),
('till', 'Anglais'),
('time', 'Anglais'),
('timetable', 'Anglais'),
('tin', 'Anglais'),
('tiny', 'Anglais'),
('tip', 'Anglais'),
('tip over', 'Anglais'),
('tire', 'Anglais'),
('tired', 'Anglais'),
('tire out', 'Anglais'),
('tiring', 'Anglais'),
('title', 'Anglais'),
('to', 'Anglais'),
('today', 'Anglais'),
('toe', 'Anglais'),
('together', 'Anglais'),
('toilet', 'Anglais'),
('tomato', 'Anglais'),
('tomorrow', 'Anglais'),
('ton', 'Anglais'),
('tone', 'Anglais'),
('tongue', 'Anglais'),
('tonight', 'Anglais'),
('tonne', 'Anglais'),
('too', 'Anglais'),
('tool', 'Anglais'),
('tooth', 'Anglais'),
('top', 'Anglais'),
('topic', 'Anglais'),
('total', 'Anglais'),
('totally', 'Anglais'),
('touch', 'Anglais'),
('tough', 'Anglais'),
('tour', 'Anglais'),
('tourist', 'Anglais'),
('towards', 'Anglais'),
('towel', 'Anglais'),
('tower', 'Anglais'),
('town', 'Anglais'),
('toy', 'Anglais'),
('trace', 'Anglais'),
('track', 'Anglais'),
('trade', 'Anglais'),
('trading', 'Anglais'),
('tradition', 'Anglais'),
('traditional', 'Anglais'),
('traditionally', 'Anglais'),
('traffic', 'Anglais'),
('train', 'Anglais'),
('training', 'Anglais'),
('transfer', 'Anglais'),
('transfer', 'Anglais'),
('transform', 'Anglais'),
('translate', 'Anglais'),
('translation', 'Anglais'),
('transparent', 'Anglais'),
('transport', 'Anglais'),
('transport', 'Anglais'),
('transportation', 'Anglais'),
('trap', 'Anglais'),
('travel', 'Anglais'),
('traveller', 'Anglais'),
('treat', 'Anglais'),
('treatment', 'Anglais'),
('tree', 'Anglais'),
('trend', 'Anglais'),
('trial', 'Anglais'),
('triangle', 'Anglais'),
('trick', 'Anglais'),
('trip', 'Anglais'),
('tropical', 'Anglais'),
('trouble', 'Anglais'),
('trousers', 'Anglais'),
('truck', 'Anglais'),
('true', 'Anglais'),
('truly', 'Anglais'),
('trust', 'Anglais'),
('truth', 'Anglais'),
('try', 'Anglais'),
('try on', 'Anglais'),
('try out', 'Anglais'),
('tube', 'Anglais'),
('Tuesday', 'Anglais'),
('tune', 'Anglais'),
('tunnel', 'Anglais'),
('turn', 'Anglais'),
('turn back', 'Anglais'),
('turn down', 'Anglais'),
('turn into', 'Anglais'),
('turn off', 'Anglais'),
('turn on', 'Anglais'),
('turn out', 'Anglais'),
('turn over', 'Anglais'),
('turn round', 'Anglais'),
('turn to', 'Anglais'),
('turn up', 'Anglais'),
('TV', 'Anglais'),
('twelfth', 'Anglais'),
('twelve', 'Anglais'),
('twentieth', 'Anglais'),
('twenty', 'Anglais'),
('twice', 'Anglais'),
('twin', 'Anglais'),
('twist', 'Anglais'),
('twisted', 'Anglais'),
('two', 'Anglais'),
('type', 'Anglais'),
('typical', 'Anglais'),
('typically', 'Anglais'),
('tyre', 'Anglais'),
('the unemployed', 'Anglais'),
('the unexpected', 'Anglais'),
('ugly', 'Anglais'),
('ultimate', 'Anglais'),
('ultimately', 'Anglais'),
('umbrella', 'Anglais'),
('unable', 'Anglais'),
('unacceptable', 'Anglais'),
('uncertain', 'Anglais'),
('uncle', 'Anglais'),
('uncomfortable', 'Anglais'),
('unconscious', 'Anglais'),
('uncontrolled', 'Anglais'),
('under', 'Anglais'),
('underground', 'Anglais'),
('underneath', 'Anglais'),
('understand', 'Anglais'),
('understanding', 'Anglais'),
('underwater', 'Anglais'),
('underwear', 'Anglais'),
('undo', 'Anglais'),
('unemployed', 'Anglais'),
('unemployment', 'Anglais'),
('unexpected', 'Anglais'),
('unexpectedly', 'Anglais'),
('unfair', 'Anglais'),
('unfairly', 'Anglais'),
('unfortunate', 'Anglais'),
('unfortunately', 'Anglais'),
('unfriendly', 'Anglais'),
('unhappy', 'Anglais'),
('uniform', 'Anglais'),
('unimportant', 'Anglais'),
('union', 'Anglais'),
('unique', 'Anglais'),
('unit', 'Anglais'),
('unite', 'Anglais'),
('united', 'Anglais'),
('universe', 'Anglais'),
('university', 'Anglais'),
('unkind', 'Anglais'),
('unknown', 'Anglais'),
('unless', 'Anglais'),
('unlike', 'Anglais'),
('unlikely', 'Anglais'),
('unload', 'Anglais'),
('unlucky', 'Anglais'),
('unnecessary', 'Anglais'),
('unpleasant', 'Anglais'),
('unreasonable', 'Anglais'),
('unsteady', 'Anglais'),
('unsuccessful', 'Anglais'),
('untidy', 'Anglais'),
('until', 'Anglais'),
('unusual', 'Anglais'),
('unusually', 'Anglais'),
('unwilling', 'Anglais'),
('unwillingly', 'Anglais'),
('up', 'Anglais'),
('upon', 'Anglais'),
('upper', 'Anglais'),
('upset', 'Anglais'),
('upset', 'Anglais'),
('upsetting', 'Anglais'),
('upside down', 'Anglais'),
('upstairs', 'Anglais'),
('upward', 'Anglais'),
('upwards', 'Anglais'),
('urban', 'Anglais'),
('urge', 'Anglais'),
('urgent', 'Anglais'),
('us', 'Anglais'),
('use', 'Anglais'),
('use', 'Anglais'),
('used 1', 'Anglais'),
('used 2', 'Anglais'),
('used to', 'Anglais'),
('useful', 'Anglais'),
('useless', 'Anglais'),
('user', 'Anglais'),
('use up', 'Anglais'),
('usual', 'Anglais'),
('usually', 'Anglais'),
('vacation', 'Anglais'),
('valid', 'Anglais'),
('valley', 'Anglais'),
('valuable', 'Anglais'),
('value', 'Anglais'),
('van', 'Anglais'),
('variation', 'Anglais'),
('varied', 'Anglais'),
('variety', 'Anglais'),
('various', 'Anglais'),
('vary', 'Anglais'),
('vast', 'Anglais'),
('vegetable', 'Anglais'),
('vehicle', 'Anglais'),
('venture', 'Anglais'),
('version', 'Anglais'),
('vertical', 'Anglais'),
('very', 'Anglais'),
('via', 'Anglais'),
('victim', 'Anglais'),
('victory', 'Anglais'),
('video', 'Anglais'),
('view', 'Anglais'),
('village', 'Anglais'),
('violence', 'Anglais'),
('violent', 'Anglais'),
('violently', 'Anglais'),
('virtually', 'Anglais'),
('virus', 'Anglais'),
('visible', 'Anglais'),
('vision', 'Anglais'),
('visit', 'Anglais'),
('visitor', 'Anglais'),
('vital', 'Anglais'),
('vocabulary', 'Anglais'),
('voice', 'Anglais'),
('volume', 'Anglais'),
('vote', 'Anglais'),
('wage', 'Anglais'),
('waist', 'Anglais'),
('wait', 'Anglais'),
('waiter', 'Anglais'),
('wake', 'Anglais'),
('walk', 'Anglais'),
('walking', 'Anglais'),
('walk out', 'Anglais'),
('walk up', 'Anglais'),
('wall', 'Anglais'),
('wallet', 'Anglais'),
('wander', 'Anglais'),
('want', 'Anglais'),
('war', 'Anglais'),
('warm', 'Anglais'),
('warmth', 'Anglais'),
('warm up', 'Anglais'),
('warn', 'Anglais'),
('warning', 'Anglais'),
('wash', 'Anglais'),
('wash away', 'Anglais'),
('washing', 'Anglais'),
('wash off', 'Anglais'),
('wash out', 'Anglais'),
('wash up', 'Anglais'),
('waste', 'Anglais'),
('watch', 'Anglais'),
('watch out', 'Anglais'),
('watch out for', 'Anglais'),
('water', 'Anglais'),
('wave', 'Anglais'),
('way', 'Anglais'),
('we', 'Anglais'),
('weak', 'Anglais'),
('weakness', 'Anglais'),
('wealth', 'Anglais'),
('weapon', 'Anglais'),
('wear', 'Anglais'),
('wear away', 'Anglais'),
('wear off', 'Anglais'),
('wear out', 'Anglais'),
('weather', 'Anglais'),
('web', 'Anglais'),
('website', 'Anglais'),
('wedding', 'Anglais'),
('Wednesday', 'Anglais'),
('week', 'Anglais'),
('weekend', 'Anglais'),
('weekly', 'Anglais'),
('weigh', 'Anglais'),
('weight', 'Anglais'),
('welcome', 'Anglais'),
('well', 'Anglais'),
('well known', 'Anglais'),
('west', 'Anglais'),
('western', 'Anglais'),
('wet', 'Anglais'),
('what', 'Anglais'),
('whatever', 'Anglais'),
('wheel', 'Anglais'),
('when', 'Anglais'),
('whenever', 'Anglais'),
('where', 'Anglais'),
('whereas', 'Anglais'),
('wherever', 'Anglais'),
('whether', 'Anglais'),
('which', 'Anglais'),
('while', 'Anglais'),
('whisper', 'Anglais'),
('whistle', 'Anglais'),
('white', 'Anglais'),
('who', 'Anglais'),
('whoever', 'Anglais'),
('whole', 'Anglais'),
('whom', 'Anglais'),
('whose', 'Anglais'),
('why', 'Anglais'),
('wide', 'Anglais'),
('widely', 'Anglais'),
('width', 'Anglais'),
('wife', 'Anglais'),
('wild', 'Anglais'),
('wildly', 'Anglais'),
('will', 'Anglais'),
('willing', 'Anglais'),
('willingly', 'Anglais'),
('willingness', 'Anglais'),
('win', 'Anglais'),
('wind 1', 'Anglais'),
('wind 2', 'Anglais'),
('window', 'Anglais'),
('wine', 'Anglais'),
('wing', 'Anglais'),
('winner', 'Anglais'),
('winning', 'Anglais'),
('winter', 'Anglais'),
('wire', 'Anglais'),
('wise', 'Anglais'),
('wish', 'Anglais'),
('with', 'Anglais'),
('withdraw', 'Anglais'),
('within', 'Anglais'),
('without', 'Anglais'),
('witness', 'Anglais'),
('woman', 'Anglais'),
('wonder', 'Anglais'),
('wonderful', 'Anglais'),
('wood', 'Anglais'),
('wooden', 'Anglais'),
('wool', 'Anglais'),
('word', 'Anglais'),
('work', 'Anglais'),
('worker', 'Anglais'),
('working', 'Anglais'),
('work out', 'Anglais'),
('world', 'Anglais'),
('worried', 'Anglais'),
('worry', 'Anglais'),
('worrying', 'Anglais'),
('worse', 'Anglais'),
('worship', 'Anglais'),
('worst', 'Anglais'),
('worth', 'Anglais'),
('would', 'Anglais'),
('wound 1', 'Anglais'),
('wounded', 'Anglais'),
('wrap', 'Anglais'),
('wrapping', 'Anglais'),
('wrist', 'Anglais'),
('write', 'Anglais'),
('write back', 'Anglais'),
('write down', 'Anglais'),
('writer', 'Anglais'),
('writing', 'Anglais'),
('written', 'Anglais'),
('wrong', 'Anglais'),
('wrongly', 'Anglais'),
('yard', 'Anglais'),
('yawn', 'Anglais'),
('yeah', 'Anglais'),
('year', 'Anglais'),
('yellow', 'Anglais'),
('yes', 'Anglais'),
('yesterday', 'Anglais'),
('yet', 'Anglais'),
('you', 'Anglais'),
('young', 'Anglais'), 
('your', 'Anglais'), 
('yours', 'Anglais'),
('yourself', 'Anglais'),
('youth', 'Anglais'), 
('zero', 'Anglais'),
('zone', 'Anglais');