<?php

namespace MotBundle\Repository;

/**
 * MotDicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotDicoRepository extends \Doctrine\ORM\EntityRepository
{
}
