<?php

namespace MotBundle\Repository;

/**
 * MotLuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotLuRepository extends \Doctrine\ORM\EntityRepository
{
}
