<?php

namespace LangueBundle\Repository;

/**
 * NiveauLangueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NiveauLangueRepository extends \Doctrine\ORM\EntityRepository
{
}
