mot:
    resource: "@MotBundle/Controller/"
    type:     annotation
    prefix:   /

dictionnaire:
    resource: "@DictionnaireBundle/Controller/"
    type:     annotation
    prefix:   /

langue:
    resource: "@LangueBundle/Controller/"
    type:     annotation
    prefix:   /

text:
    resource: "@TextBundle/Controller/"
    type:     annotation
    prefix:   /

index:
    resource: "@IndexBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
