# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    user.form.registration:
        class: UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: user_user_registration }
