<?php

namespace DictionnaireBundle\Repository;

/**
 * DictionnaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DictionnaireRepository extends \Doctrine\ORM\EntityRepository
{
}
